"""Wire protocol between the Python SDK and taskwire-agent.

Re-exports the supported frame API, schema types, codec functions, and
errors. Importing ``taskwire`` remains independent of the optional
acceleration module.
"""

from taskwire.protocol.errors import (
    ERROR_RETRYABLE,
    FrameTooLarge,
    ProtocolDecodeError,
    TruncatedFrame,
)
from taskwire.protocol.frames import (
    HEADER_SIZE,
    MAX_UINT32,
    PROTOCOL_VERSION,
    Flag,
    Frame,
    FrameHeader,
    MessageType,
    decode_header,
    encode_frame,
    read_frame,
)
from taskwire.protocol.messages import (
    Ack,
    CancelRequest,
    Completion,
    Error,
    Failure,
    ForwardedCompletion,
    ForwardedTask,
    HeartbeatRequest,
    Hello,
    LeasedTask,
    ObjectChunk,
    ObjectGetRequest,
    ObjectPutRequest,
    ObjectRef,
    PullRequest,
    ResultNotification,
    ResumeResultsRequest,
    StatusRequest,
    StatusSnapshot,
    StealRequest,
    TaskEnvelope,
    TaskCapability,
    TaskRegistration,
    TaskQuery,
    TaskSnapshot,
    TaskSnapshotEntry,
    ValueRef,
    decode_payload,
    decode_portable_value,
    encode_payload,
    encode_portable_value,
    make_ack,
)
from taskwire.protocol.session import ConnectionState, OwnerRegistry, Session

__all__ = [
    "ERROR_RETRYABLE",
    "FrameTooLarge",
    "ProtocolDecodeError",
    "TruncatedFrame",
    "HEADER_SIZE",
    "MAX_UINT32",
    "PROTOCOL_VERSION",
    "Flag",
    "Frame",
    "FrameHeader",
    "MessageType",
    "decode_header",
    "encode_frame",
    "read_frame",
    "Ack",
    "CancelRequest",
    "Completion",
    "Error",
    "Failure",
    "ForwardedCompletion",
    "ForwardedTask",
    "HeartbeatRequest",
    "Hello",
    "LeasedTask",
    "ObjectChunk",
    "ObjectGetRequest",
    "ObjectPutRequest",
    "ObjectRef",
    "PullRequest",
    "ResultNotification",
    "ResumeResultsRequest",
    "StatusRequest",
    "StatusSnapshot",
    "StealRequest",
    "TaskEnvelope",
    "TaskCapability",
    "TaskRegistration",
    "TaskQuery",
    "TaskSnapshot",
    "TaskSnapshotEntry",
    "ValueRef",
    "decode_payload",
    "decode_portable_value",
    "encode_payload",
    "encode_portable_value",
    "make_ack",
    "ConnectionState",
    "OwnerRegistry",
    "Session",
]
