// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.13.0
// source: taskwire/v1/control.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorkerMessage is the worker-to-agent branch of the Work stream.
type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*WorkerMessage_Register
	//	*WorkerMessage_Pull
	//	*WorkerMessage_Heartbeat
	//	*WorkerMessage_Complete
	//	*WorkerMessage_UpdateTasks
	Body          isWorkerMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_taskwire_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetBody() isWorkerMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *WorkerMessage) GetRegister() *WorkerRegistration {
	if x != nil {
		if x, ok := x.Body.(*WorkerMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *WorkerMessage) GetPull() *PullRequest {
	if x != nil {
		if x, ok := x.Body.(*WorkerMessage_Pull); ok {
			return x.Pull
		}
	}
	return nil
}

func (x *WorkerMessage) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Body.(*WorkerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerMessage) GetComplete() *Completion {
	if x != nil {
		if x, ok := x.Body.(*WorkerMessage_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

func (x *WorkerMessage) GetUpdateTasks() *TaskRegistration {
	if x != nil {
		if x, ok := x.Body.(*WorkerMessage_UpdateTasks); ok {
			return x.UpdateTasks
		}
	}
	return nil
}

type isWorkerMessage_Body interface {
	isWorkerMessage_Body()
}

type WorkerMessage_Register struct {
	Register *WorkerRegistration `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type WorkerMessage_Pull struct {
	Pull *PullRequest `protobuf:"bytes,2,opt,name=pull,proto3,oneof"`
}

type WorkerMessage_Heartbeat struct {
	Heartbeat *HeartbeatRequest `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type WorkerMessage_Complete struct {
	Complete *Completion `protobuf:"bytes,4,opt,name=complete,proto3,oneof"`
}

type WorkerMessage_UpdateTasks struct {
	UpdateTasks *TaskRegistration `protobuf:"bytes,5,opt,name=update_tasks,json=updateTasks,proto3,oneof"`
}

func (*WorkerMessage_Register) isWorkerMessage_Body() {}

func (*WorkerMessage_Pull) isWorkerMessage_Body() {}

func (*WorkerMessage_Heartbeat) isWorkerMessage_Body() {}

func (*WorkerMessage_Complete) isWorkerMessage_Body() {}

func (*WorkerMessage_UpdateTasks) isWorkerMessage_Body() {}

// AgentMessage is the agent-to-worker branch of the Work stream.
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*AgentMessage_Task
	//	*AgentMessage_HeartbeatAck
	//	*AgentMessage_CompleteAck
	//	*AgentMessage_Registered
	Body          isAgentMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_taskwire_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *AgentMessage) GetBody() isAgentMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AgentMessage) GetTask() *LeasedTask {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeatAck() *HeartbeatResponse {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *AgentMessage) GetCompleteAck() *CompletionResponse {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_CompleteAck); ok {
			return x.CompleteAck
		}
	}
	return nil
}

func (x *AgentMessage) GetRegistered() *WorkerRegistrationResponse {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Registered); ok {
			return x.Registered
		}
	}
	return nil
}

type isAgentMessage_Body interface {
	isAgentMessage_Body()
}

type AgentMessage_Task struct {
	Task *LeasedTask `protobuf:"bytes,1,opt,name=task,proto3,oneof"`
}

type AgentMessage_HeartbeatAck struct {
	HeartbeatAck *HeartbeatResponse `protobuf:"bytes,2,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type AgentMessage_CompleteAck struct {
	CompleteAck *CompletionResponse `protobuf:"bytes,3,opt,name=complete_ack,json=completeAck,proto3,oneof"`
}

type AgentMessage_Registered struct {
	Registered *WorkerRegistrationResponse `protobuf:"bytes,4,opt,name=registered,proto3,oneof"`
}

func (*AgentMessage_Task) isAgentMessage_Body() {}

func (*AgentMessage_HeartbeatAck) isAgentMessage_Body() {}

func (*AgentMessage_CompleteAck) isAgentMessage_Body() {}

func (*AgentMessage_Registered) isAgentMessage_Body() {}

// WorkerRegistration is the first Work message and establishes immutable
// stream identity plus the initial complete capability set.
type WorkerRegistration struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkerId       string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Runtime        string                 `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	RuntimeVersion string                 `protobuf:"bytes,3,opt,name=runtime_version,json=runtimeVersion,proto3" json:"runtime_version,omitempty"`
	SdkVersion     string                 `protobuf:"bytes,4,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	Codecs         []string               `protobuf:"bytes,5,rep,name=codecs,proto3" json:"codecs,omitempty"`
	Tasks          *TaskRegistration      `protobuf:"bytes,6,opt,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkerRegistration) Reset() {
	*x = WorkerRegistration{}
	mi := &file_taskwire_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRegistration) ProtoMessage() {}

func (x *WorkerRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRegistration.ProtoReflect.Descriptor instead.
func (*WorkerRegistration) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerRegistration) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerRegistration) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *WorkerRegistration) GetRuntimeVersion() string {
	if x != nil {
		return x.RuntimeVersion
	}
	return ""
}

func (x *WorkerRegistration) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *WorkerRegistration) GetCodecs() []string {
	if x != nil {
		return x.Codecs
	}
	return nil
}

func (x *WorkerRegistration) GetTasks() *TaskRegistration {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type WorkerRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	Accepted      uint32                 `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerRegistrationResponse) Reset() {
	*x = WorkerRegistrationResponse{}
	mi := &file_taskwire_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRegistrationResponse) ProtoMessage() {}

func (x *WorkerRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRegistrationResponse.ProtoReflect.Descriptor instead.
func (*WorkerRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *WorkerRegistrationResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerRegistrationResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *WorkerRegistrationResponse) GetAccepted() uint32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

type ObjectRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        []byte                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Codec         string                 `protobuf:"bytes,5,opt,name=codec,proto3" json:"codec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectRef) Reset() {
	*x = ObjectRef{}
	mi := &file_taskwire_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRef) ProtoMessage() {}

func (x *ObjectRef) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRef.ProtoReflect.Descriptor instead.
func (*ObjectRef) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *ObjectRef) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *ObjectRef) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ObjectRef) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ObjectRef) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *ObjectRef) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

type ValueRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Location:
	//
	//	*ValueRef_Inline
	//	*ValueRef_Object
	Location      isValueRef_Location `protobuf_oneof:"location"`
	Codec         string              `protobuf:"bytes,3,opt,name=codec,proto3" json:"codec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueRef) Reset() {
	*x = ValueRef{}
	mi := &file_taskwire_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueRef) ProtoMessage() {}

func (x *ValueRef) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueRef.ProtoReflect.Descriptor instead.
func (*ValueRef) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *ValueRef) GetLocation() isValueRef_Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *ValueRef) GetInline() []byte {
	if x != nil {
		if x, ok := x.Location.(*ValueRef_Inline); ok {
			return x.Inline
		}
	}
	return nil
}

func (x *ValueRef) GetObject() *ObjectRef {
	if x != nil {
		if x, ok := x.Location.(*ValueRef_Object); ok {
			return x.Object
		}
	}
	return nil
}

func (x *ValueRef) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

type isValueRef_Location interface {
	isValueRef_Location()
}

type ValueRef_Inline struct {
	Inline []byte `protobuf:"bytes,1,opt,name=inline,proto3,oneof"`
}

type ValueRef_Object struct {
	Object *ObjectRef `protobuf:"bytes,2,opt,name=object,proto3,oneof"`
}

func (*ValueRef_Inline) isValueRef_Location() {}

func (*ValueRef_Object) isValueRef_Location() {}

type PullRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WorkerId             string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CapabilityGeneration uint64                 `protobuf:"varint,2,opt,name=capability_generation,json=capabilityGeneration,proto3" json:"capability_generation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_taskwire_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *PullRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *PullRequest) GetCapabilityGeneration() uint64 {
	if x != nil {
		return x.CapabilityGeneration
	}
	return 0
}

type TaskCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskName      string                 `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	TaskVersion   string                 `protobuf:"bytes,2,opt,name=task_version,json=taskVersion,proto3" json:"task_version,omitempty"`
	Invocation    string                 `protobuf:"bytes,3,opt,name=invocation,proto3" json:"invocation,omitempty"`
	Codecs        []string               `protobuf:"bytes,4,rep,name=codecs,proto3" json:"codecs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCapability) Reset() {
	*x = TaskCapability{}
	mi := &file_taskwire_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCapability) ProtoMessage() {}

func (x *TaskCapability) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCapability.ProtoReflect.Descriptor instead.
func (*TaskCapability) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *TaskCapability) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *TaskCapability) GetTaskVersion() string {
	if x != nil {
		return x.TaskVersion
	}
	return ""
}

func (x *TaskCapability) GetInvocation() string {
	if x != nil {
		return x.Invocation
	}
	return ""
}

func (x *TaskCapability) GetCodecs() []string {
	if x != nil {
		return x.Codecs
	}
	return nil
}

type TaskRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	Tasks         []*TaskCapability      `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRegistration) Reset() {
	*x = TaskRegistration{}
	mi := &file_taskwire_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRegistration) ProtoMessage() {}

func (x *TaskRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRegistration.ProtoReflect.Descriptor instead.
func (*TaskRegistration) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *TaskRegistration) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskRegistration) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *TaskRegistration) GetTasks() []*TaskCapability {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type TaskQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       []byte                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	TaskIds       [][]byte               `protobuf:"bytes,2,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskQuery) Reset() {
	*x = TaskQuery{}
	mi := &file_taskwire_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskQuery) ProtoMessage() {}

func (x *TaskQuery) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskQuery.ProtoReflect.Descriptor instead.
func (*TaskQuery) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *TaskQuery) GetOwnerId() []byte {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *TaskQuery) GetTaskIds() [][]byte {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

type TaskSnapshotEntry struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TaskId []byte                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	State  string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Cursor *uint64                `protobuf:"varint,3,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*TaskSnapshotEntry_Result
	//	*TaskSnapshotEntry_Failure
	Outcome       isTaskSnapshotEntry_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSnapshotEntry) Reset() {
	*x = TaskSnapshotEntry{}
	mi := &file_taskwire_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSnapshotEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSnapshotEntry) ProtoMessage() {}

func (x *TaskSnapshotEntry) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSnapshotEntry.ProtoReflect.Descriptor instead.
func (*TaskSnapshotEntry) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *TaskSnapshotEntry) GetTaskId() []byte {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *TaskSnapshotEntry) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TaskSnapshotEntry) GetCursor() uint64 {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return 0
}

func (x *TaskSnapshotEntry) GetOutcome() isTaskSnapshotEntry_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *TaskSnapshotEntry) GetResult() *ObjectRef {
	if x != nil {
		if x, ok := x.Outcome.(*TaskSnapshotEntry_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *TaskSnapshotEntry) GetFailure() *Failure {
	if x != nil {
		if x, ok := x.Outcome.(*TaskSnapshotEntry_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isTaskSnapshotEntry_Outcome interface {
	isTaskSnapshotEntry_Outcome()
}

type TaskSnapshotEntry_Result struct {
	Result *ObjectRef `protobuf:"bytes,4,opt,name=result,proto3,oneof"`
}

type TaskSnapshotEntry_Failure struct {
	Failure *Failure `protobuf:"bytes,5,opt,name=failure,proto3,oneof"`
}

func (*TaskSnapshotEntry_Result) isTaskSnapshotEntry_Outcome() {}

func (*TaskSnapshotEntry_Failure) isTaskSnapshotEntry_Outcome() {}

type TaskSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskSnapshotEntry   `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSnapshot) Reset() {
	*x = TaskSnapshot{}
	mi := &file_taskwire_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSnapshot) ProtoMessage() {}

func (x *TaskSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSnapshot.ProtoReflect.Descriptor instead.
func (*TaskSnapshot) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{11}
}

func (x *TaskSnapshot) GetTasks() []*TaskSnapshotEntry {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type TaskEnvelope struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OwnerId           []byte                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	TaskName          string                 `protobuf:"bytes,2,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	TaskVersion       string                 `protobuf:"bytes,3,opt,name=task_version,json=taskVersion,proto3" json:"task_version,omitempty"`
	Invocation        string                 `protobuf:"bytes,4,opt,name=invocation,proto3" json:"invocation,omitempty"`
	Input             *ValueRef              `protobuf:"bytes,5,opt,name=input,proto3" json:"input,omitempty"`
	Labels            map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Idempotent        bool                   `protobuf:"varint,7,opt,name=idempotent,proto3" json:"idempotent,omitempty"`
	SubmittedAtUnixMs int64                  `protobuf:"varint,8,opt,name=submitted_at_unix_ms,json=submittedAtUnixMs,proto3" json:"submitted_at_unix_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskEnvelope) Reset() {
	*x = TaskEnvelope{}
	mi := &file_taskwire_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEnvelope) ProtoMessage() {}

func (x *TaskEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEnvelope.ProtoReflect.Descriptor instead.
func (*TaskEnvelope) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{12}
}

func (x *TaskEnvelope) GetOwnerId() []byte {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *TaskEnvelope) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *TaskEnvelope) GetTaskVersion() string {
	if x != nil {
		return x.TaskVersion
	}
	return ""
}

func (x *TaskEnvelope) GetInvocation() string {
	if x != nil {
		return x.Invocation
	}
	return ""
}

func (x *TaskEnvelope) GetInput() *ValueRef {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *TaskEnvelope) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *TaskEnvelope) GetIdempotent() bool {
	if x != nil {
		return x.Idempotent
	}
	return false
}

func (x *TaskEnvelope) GetSubmittedAtUnixMs() int64 {
	if x != nil {
		return x.SubmittedAtUnixMs
	}
	return 0
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        []byte                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_taskwire_v1_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{13}
}

func (x *SubmitResponse) GetTaskId() []byte {
	if x != nil {
		return x.TaskId
	}
	return nil
}

type LeasedTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *TaskEnvelope          `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	TaskId        []byte                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LeaseId       []byte                 `protobuf:"bytes,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	TtlMs         uint32                 `protobuf:"varint,4,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	Attempt       uint32                 `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeasedTask) Reset() {
	*x = LeasedTask{}
	mi := &file_taskwire_v1_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeasedTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeasedTask) ProtoMessage() {}

func (x *LeasedTask) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeasedTask.ProtoReflect.Descriptor instead.
func (*LeasedTask) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{14}
}

func (x *LeasedTask) GetTask() *TaskEnvelope {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *LeasedTask) GetTaskId() []byte {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *LeasedTask) GetLeaseId() []byte {
	if x != nil {
		return x.LeaseId
	}
	return nil
}

func (x *LeasedTask) GetTtlMs() uint32 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

func (x *LeasedTask) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type Completion struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	LeaseId []byte                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*Completion_Result
	//	*Completion_Failure
	Outcome       isCompletion_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Completion) Reset() {
	*x = Completion{}
	mi := &file_taskwire_v1_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Completion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Completion) ProtoMessage() {}

func (x *Completion) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Completion.ProtoReflect.Descriptor instead.
func (*Completion) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{15}
}

func (x *Completion) GetLeaseId() []byte {
	if x != nil {
		return x.LeaseId
	}
	return nil
}

func (x *Completion) GetOutcome() isCompletion_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *Completion) GetResult() *ObjectRef {
	if x != nil {
		if x, ok := x.Outcome.(*Completion_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *Completion) GetFailure() *Failure {
	if x != nil {
		if x, ok := x.Outcome.(*Completion_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isCompletion_Outcome interface {
	isCompletion_Outcome()
}

type Completion_Result struct {
	Result *ObjectRef `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type Completion_Failure struct {
	Failure *Failure `protobuf:"bytes,3,opt,name=failure,proto3,oneof"`
}

func (*Completion_Result) isCompletion_Outcome() {}

func (*Completion_Failure) isCompletion_Outcome() {}

type CompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       []byte                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionResponse) Reset() {
	*x = CompletionResponse{}
	mi := &file_taskwire_v1_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionResponse) ProtoMessage() {}

func (x *CompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionResponse.ProtoReflect.Descriptor instead.
func (*CompletionResponse) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{16}
}

func (x *CompletionResponse) GetLeaseId() []byte {
	if x != nil {
		return x.LeaseId
	}
	return nil
}

type ForwardedTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    []byte                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	OriginNode    string                 `protobuf:"bytes,2,opt,name=origin_node,json=originNode,proto3" json:"origin_node,omitempty"`
	Task          *TaskEnvelope          `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardedTask) Reset() {
	*x = ForwardedTask{}
	mi := &file_taskwire_v1_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardedTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardedTask) ProtoMessage() {}

func (x *ForwardedTask) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardedTask.ProtoReflect.Descriptor instead.
func (*ForwardedTask) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{17}
}

func (x *ForwardedTask) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *ForwardedTask) GetOriginNode() string {
	if x != nil {
		return x.OriginNode
	}
	return ""
}

func (x *ForwardedTask) GetTask() *TaskEnvelope {
	if x != nil {
		return x.Task
	}
	return nil
}

type ForwardTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        []byte                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TransferId    []byte                 `protobuf:"bytes,2,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardTaskResponse) Reset() {
	*x = ForwardTaskResponse{}
	mi := &file_taskwire_v1_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardTaskResponse) ProtoMessage() {}

func (x *ForwardTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardTaskResponse.ProtoReflect.Descriptor instead.
func (*ForwardTaskResponse) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{18}
}

func (x *ForwardTaskResponse) GetTaskId() []byte {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *ForwardTaskResponse) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

type ForwardedCompletion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    []byte                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	RemoteNode    string                 `protobuf:"bytes,2,opt,name=remote_node,json=remoteNode,proto3" json:"remote_node,omitempty"`
	RemoteAttempt uint32                 `protobuf:"varint,3,opt,name=remote_attempt,json=remoteAttempt,proto3" json:"remote_attempt,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*ForwardedCompletion_Result
	//	*ForwardedCompletion_Failure
	Outcome       isForwardedCompletion_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardedCompletion) Reset() {
	*x = ForwardedCompletion{}
	mi := &file_taskwire_v1_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardedCompletion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardedCompletion) ProtoMessage() {}

func (x *ForwardedCompletion) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardedCompletion.ProtoReflect.Descriptor instead.
func (*ForwardedCompletion) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{19}
}

func (x *ForwardedCompletion) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *ForwardedCompletion) GetRemoteNode() string {
	if x != nil {
		return x.RemoteNode
	}
	return ""
}

func (x *ForwardedCompletion) GetRemoteAttempt() uint32 {
	if x != nil {
		return x.RemoteAttempt
	}
	return 0
}

func (x *ForwardedCompletion) GetOutcome() isForwardedCompletion_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *ForwardedCompletion) GetResult() *ObjectRef {
	if x != nil {
		if x, ok := x.Outcome.(*ForwardedCompletion_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ForwardedCompletion) GetFailure() *Failure {
	if x != nil {
		if x, ok := x.Outcome.(*ForwardedCompletion_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isForwardedCompletion_Outcome interface {
	isForwardedCompletion_Outcome()
}

type ForwardedCompletion_Result struct {
	Result *ObjectRef `protobuf:"bytes,4,opt,name=result,proto3,oneof"`
}

type ForwardedCompletion_Failure struct {
	Failure *Failure `protobuf:"bytes,5,opt,name=failure,proto3,oneof"`
}

func (*ForwardedCompletion_Result) isForwardedCompletion_Outcome() {}

func (*ForwardedCompletion_Failure) isForwardedCompletion_Outcome() {}

type ForwardCompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    []byte                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardCompletionResponse) Reset() {
	*x = ForwardCompletionResponse{}
	mi := &file_taskwire_v1_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardCompletionResponse) ProtoMessage() {}

func (x *ForwardCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardCompletionResponse.ProtoReflect.Descriptor instead.
func (*ForwardCompletionResponse) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{20}
}

func (x *ForwardCompletionResponse) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

type Failure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       *ValueRef              `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_taskwire_v1_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{21}
}

func (x *Failure) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Failure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Failure) GetDetails() *ValueRef {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Failure) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type ResultNotification struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	OwnerId []byte                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	TaskId  []byte                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Cursor  uint64                 `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	State   string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*ResultNotification_Result
	//	*ResultNotification_Failure
	Outcome       isResultNotification_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultNotification) Reset() {
	*x = ResultNotification{}
	mi := &file_taskwire_v1_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultNotification) ProtoMessage() {}

func (x *ResultNotification) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultNotification.ProtoReflect.Descriptor instead.
func (*ResultNotification) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{22}
}

func (x *ResultNotification) GetOwnerId() []byte {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *ResultNotification) GetTaskId() []byte {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *ResultNotification) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ResultNotification) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ResultNotification) GetOutcome() isResultNotification_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *ResultNotification) GetResult() *ObjectRef {
	if x != nil {
		if x, ok := x.Outcome.(*ResultNotification_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ResultNotification) GetFailure() *Failure {
	if x != nil {
		if x, ok := x.Outcome.(*ResultNotification_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isResultNotification_Outcome interface {
	isResultNotification_Outcome()
}

type ResultNotification_Result struct {
	Result *ObjectRef `protobuf:"bytes,5,opt,name=result,proto3,oneof"`
}

type ResultNotification_Failure struct {
	Failure *Failure `protobuf:"bytes,6,opt,name=failure,proto3,oneof"`
}

func (*ResultNotification_Result) isResultNotification_Outcome() {}

func (*ResultNotification_Failure) isResultNotification_Outcome() {}

type WatchResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       []byte                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	AfterCursor   uint64                 `protobuf:"varint,2,opt,name=after_cursor,json=afterCursor,proto3" json:"after_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResultsRequest) Reset() {
	*x = WatchResultsRequest{}
	mi := &file_taskwire_v1_control_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResultsRequest) ProtoMessage() {}

func (x *WatchResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResultsRequest.ProtoReflect.Descriptor instead.
func (*WatchResultsRequest) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{23}
}

func (x *WatchResultsRequest) GetOwnerId() []byte {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *WatchResultsRequest) GetAfterCursor() uint64 {
	if x != nil {
		return x.AfterCursor
	}
	return 0
}

type AckResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       []byte                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	TaskId        []byte                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Cursor        uint64                 `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResultRequest) Reset() {
	*x = AckResultRequest{}
	mi := &file_taskwire_v1_control_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResultRequest) ProtoMessage() {}

func (x *AckResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResultRequest.ProtoReflect.Descriptor instead.
func (*AckResultRequest) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{24}
}

func (x *AckResultRequest) GetOwnerId() []byte {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *AckResultRequest) GetTaskId() []byte {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *AckResultRequest) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

type AckResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResultResponse) Reset() {
	*x = AckResultResponse{}
	mi := &file_taskwire_v1_control_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResultResponse) ProtoMessage() {}

func (x *AckResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResultResponse.ProtoReflect.Descriptor instead.
func (*AckResultResponse) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{25}
}

type StatusSnapshot struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Version            string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Pid                uint64                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Ready              bool                   `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
	TaskCounts         map[string]uint64      `protobuf:"bytes,4,rep,name=task_counts,json=taskCounts,proto3" json:"task_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ActiveLeases       uint64                 `protobuf:"varint,5,opt,name=active_leases,json=activeLeases,proto3" json:"active_leases,omitempty"`
	WorkerPids         []uint64               `protobuf:"varint,6,rep,packed,name=worker_pids,json=workerPids,proto3" json:"worker_pids,omitempty"`
	WorkerRestarts     uint64                 `protobuf:"varint,7,opt,name=worker_restarts,json=workerRestarts,proto3" json:"worker_restarts,omitempty"`
	StorageHealthy     bool                   `protobuf:"varint,8,opt,name=storage_healthy,json=storageHealthy,proto3" json:"storage_healthy,omitempty"`
	ClusterMembers     uint64                 `protobuf:"varint,9,opt,name=cluster_members,json=clusterMembers,proto3" json:"cluster_members,omitempty"`
	KafkaOutboxPending uint64                 `protobuf:"varint,10,opt,name=kafka_outbox_pending,json=kafkaOutboxPending,proto3" json:"kafka_outbox_pending,omitempty"`
	LastErrorCode      *string                `protobuf:"bytes,11,opt,name=last_error_code,json=lastErrorCode,proto3,oneof" json:"last_error_code,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StatusSnapshot) Reset() {
	*x = StatusSnapshot{}
	mi := &file_taskwire_v1_control_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusSnapshot) ProtoMessage() {}

func (x *StatusSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusSnapshot.ProtoReflect.Descriptor instead.
func (*StatusSnapshot) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{26}
}

func (x *StatusSnapshot) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusSnapshot) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *StatusSnapshot) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *StatusSnapshot) GetTaskCounts() map[string]uint64 {
	if x != nil {
		return x.TaskCounts
	}
	return nil
}

func (x *StatusSnapshot) GetActiveLeases() uint64 {
	if x != nil {
		return x.ActiveLeases
	}
	return 0
}

func (x *StatusSnapshot) GetWorkerPids() []uint64 {
	if x != nil {
		return x.WorkerPids
	}
	return nil
}

func (x *StatusSnapshot) GetWorkerRestarts() uint64 {
	if x != nil {
		return x.WorkerRestarts
	}
	return 0
}

func (x *StatusSnapshot) GetStorageHealthy() bool {
	if x != nil {
		return x.StorageHealthy
	}
	return false
}

func (x *StatusSnapshot) GetClusterMembers() uint64 {
	if x != nil {
		return x.ClusterMembers
	}
	return 0
}

func (x *StatusSnapshot) GetKafkaOutboxPending() uint64 {
	if x != nil {
		return x.KafkaOutboxPending
	}
	return 0
}

func (x *StatusSnapshot) GetLastErrorCode() string {
	if x != nil && x.LastErrorCode != nil {
		return *x.LastErrorCode
	}
	return ""
}

// Error is carried in gRPC status details so a stable Taskwire code and
// retryability survive alongside the transport status code.
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Details       map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_taskwire_v1_control_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{27}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *Error) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       []byte                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_taskwire_v1_control_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{28}
}

func (x *HeartbeatRequest) GetLeaseId() []byte {
	if x != nil {
		return x.LeaseId
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       []byte                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_taskwire_v1_control_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{29}
}

func (x *HeartbeatResponse) GetLeaseId() []byte {
	if x != nil {
		return x.LeaseId
	}
	return nil
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       []byte                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	TaskId        []byte                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_taskwire_v1_control_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{30}
}

func (x *CancelRequest) GetOwnerId() []byte {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *CancelRequest) GetTaskId() []byte {
	if x != nil {
		return x.TaskId
	}
	return nil
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        []byte                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Cancelled     bool                   `protobuf:"varint,2,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_taskwire_v1_control_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{31}
}

func (x *CancelResponse) GetTaskId() []byte {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *CancelResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

type ObjectGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *ObjectRef             `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectGetRequest) Reset() {
	*x = ObjectGetRequest{}
	mi := &file_taskwire_v1_control_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectGetRequest) ProtoMessage() {}

func (x *ObjectGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectGetRequest.ProtoReflect.Descriptor instead.
func (*ObjectGetRequest) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{32}
}

func (x *ObjectGetRequest) GetObject() *ObjectRef {
	if x != nil {
		return x.Object
	}
	return nil
}

type PutObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *ObjectRef             `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutObjectResponse) Reset() {
	*x = PutObjectResponse{}
	mi := &file_taskwire_v1_control_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutObjectResponse) ProtoMessage() {}

func (x *PutObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutObjectResponse.ProtoReflect.Descriptor instead.
func (*PutObjectResponse) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{33}
}

func (x *PutObjectResponse) GetObject() *ObjectRef {
	if x != nil {
		return x.Object
	}
	return nil
}

// ObjectChunk carries object content. The first chunk of a PutObject stream
// sets metadata (codec, size, sha256); subsequent chunks carry data only.
// gRPC delivers chunks in order, so an explicit sequence number is no longer
// part of the contract.
type ObjectChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Codec         string                 `protobuf:"bytes,2,opt,name=codec,proto3" json:"codec,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        []byte                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectChunk) Reset() {
	*x = ObjectChunk{}
	mi := &file_taskwire_v1_control_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectChunk) ProtoMessage() {}

func (x *ObjectChunk) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectChunk.ProtoReflect.Descriptor instead.
func (*ObjectChunk) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{34}
}

func (x *ObjectChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ObjectChunk) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *ObjectChunk) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ObjectChunk) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

type StealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterNode string                 `protobuf:"bytes,1,opt,name=requester_node,json=requesterNode,proto3" json:"requester_node,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StealRequest) Reset() {
	*x = StealRequest{}
	mi := &file_taskwire_v1_control_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StealRequest) ProtoMessage() {}

func (x *StealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StealRequest.ProtoReflect.Descriptor instead.
func (*StealRequest) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{35}
}

func (x *StealRequest) GetRequesterNode() string {
	if x != nil {
		return x.RequesterNode
	}
	return ""
}

func (x *StealRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *StealRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type StealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    []byte                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Accepted      uint32                 `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StealResponse) Reset() {
	*x = StealResponse{}
	mi := &file_taskwire_v1_control_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StealResponse) ProtoMessage() {}

func (x *StealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StealResponse.ProtoReflect.Descriptor instead.
func (*StealResponse) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{36}
}

func (x *StealResponse) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *StealResponse) GetAccepted() uint32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_taskwire_v1_control_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{37}
}

var File_taskwire_v1_control_proto protoreflect.FileDescriptor

const file_taskwire_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x19taskwire/v1/control.proto\x12\vtaskwire.v1\"\xc0\x02\n" +
	"\rWorkerMessage\x12=\n" +
	"\bregister\x18\x01 \x01(\v2\x1f.taskwire.v1.WorkerRegistrationH\x00R\bregister\x12.\n" +
	"\x04pull\x18\x02 \x01(\v2\x18.taskwire.v1.PullRequestH\x00R\x04pull\x12=\n" +
	"\theartbeat\x18\x03 \x01(\v2\x1d.taskwire.v1.HeartbeatRequestH\x00R\theartbeat\x125\n" +
	"\bcomplete\x18\x04 \x01(\v2\x17.taskwire.v1.CompletionH\x00R\bcomplete\x12B\n" +
	"\fupdate_tasks\x18\x05 \x01(\v2\x1d.taskwire.v1.TaskRegistrationH\x00R\vupdateTasksB\x06\n" +
	"\x04body\"\x9d\x02\n" +
	"\fAgentMessage\x12-\n" +
	"\x04task\x18\x01 \x01(\v2\x17.taskwire.v1.LeasedTaskH\x00R\x04task\x12E\n" +
	"\rheartbeat_ack\x18\x02 \x01(\v2\x1e.taskwire.v1.HeartbeatResponseH\x00R\fheartbeatAck\x12D\n" +
	"\fcomplete_ack\x18\x03 \x01(\v2\x1f.taskwire.v1.CompletionResponseH\x00R\vcompleteAck\x12I\n" +
	"\n" +
	"registered\x18\x04 \x01(\v2'.taskwire.v1.WorkerRegistrationResponseH\x00R\n" +
	"registeredB\x06\n" +
	"\x04body\"\xe2\x01\n" +
	"\x12WorkerRegistration\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x18\n" +
	"\aruntime\x18\x02 \x01(\tR\aruntime\x12'\n" +
	"\x0fruntime_version\x18\x03 \x01(\tR\x0eruntimeVersion\x12\x1f\n" +
	"\vsdk_version\x18\x04 \x01(\tR\n" +
	"sdkVersion\x12\x16\n" +
	"\x06codecs\x18\x05 \x03(\tR\x06codecs\x123\n" +
	"\x05tasks\x18\x06 \x01(\v2\x1d.taskwire.v1.TaskRegistrationR\x05tasks\"u\n" +
	"\x1aWorkerRegistrationResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\rR\baccepted\"u\n" +
	"\tObjectRef\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\fR\x06sha256\x12\x14\n" +
	"\x05codec\x18\x05 \x01(\tR\x05codec\"x\n" +
	"\bValueRef\x12\x18\n" +
	"\x06inline\x18\x01 \x01(\fH\x00R\x06inline\x120\n" +
	"\x06object\x18\x02 \x01(\v2\x16.taskwire.v1.ObjectRefH\x00R\x06object\x12\x14\n" +
	"\x05codec\x18\x03 \x01(\tR\x05codecB\n" +
	"\n" +
	"\blocation\"_\n" +
	"\vPullRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x123\n" +
	"\x15capability_generation\x18\x02 \x01(\x04R\x14capabilityGeneration\"\x88\x01\n" +
	"\x0eTaskCapability\x12\x1b\n" +
	"\ttask_name\x18\x01 \x01(\tR\btaskName\x12!\n" +
	"\ftask_version\x18\x02 \x01(\tR\vtaskVersion\x12\x1e\n" +
	"\n" +
	"invocation\x18\x03 \x01(\tR\n" +
	"invocation\x12\x16\n" +
	"\x06codecs\x18\x04 \x03(\tR\x06codecs\"\x82\x01\n" +
	"\x10TaskRegistration\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x121\n" +
	"\x05tasks\x18\x03 \x03(\v2\x1b.taskwire.v1.TaskCapabilityR\x05tasks\"A\n" +
	"\tTaskQuery\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\fR\aownerId\x12\x19\n" +
	"\btask_ids\x18\x02 \x03(\fR\ataskIds\"\xd9\x01\n" +
	"\x11TaskSnapshotEntry\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\fR\x06taskId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1b\n" +
	"\x06cursor\x18\x03 \x01(\x04H\x01R\x06cursor\x88\x01\x01\x120\n" +
	"\x06result\x18\x04 \x01(\v2\x16.taskwire.v1.ObjectRefH\x00R\x06result\x120\n" +
	"\afailure\x18\x05 \x01(\v2\x14.taskwire.v1.FailureH\x00R\afailureB\t\n" +
	"\aoutcomeB\t\n" +
	"\a_cursor\"D\n" +
	"\fTaskSnapshot\x124\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1e.taskwire.v1.TaskSnapshotEntryR\x05tasks\"\x81\x03\n" +
	"\fTaskEnvelope\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\fR\aownerId\x12\x1b\n" +
	"\ttask_name\x18\x02 \x01(\tR\btaskName\x12!\n" +
	"\ftask_version\x18\x03 \x01(\tR\vtaskVersion\x12\x1e\n" +
	"\n" +
	"invocation\x18\x04 \x01(\tR\n" +
	"invocation\x12+\n" +
	"\x05input\x18\x05 \x01(\v2\x15.taskwire.v1.ValueRefR\x05input\x12=\n" +
	"\x06labels\x18\x06 \x03(\v2%.taskwire.v1.TaskEnvelope.LabelsEntryR\x06labels\x12\x1e\n" +
	"\n" +
	"idempotent\x18\a \x01(\bR\n" +
	"idempotent\x12/\n" +
	"\x14submitted_at_unix_ms\x18\b \x01(\x03R\x11submittedAtUnixMs\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\x0eSubmitResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\fR\x06taskId\"\xa0\x01\n" +
	"\n" +
	"LeasedTask\x12-\n" +
	"\x04task\x18\x01 \x01(\v2\x19.taskwire.v1.TaskEnvelopeR\x04task\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\fR\x06taskId\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\fR\aleaseId\x12\x15\n" +
	"\x06ttl_ms\x18\x04 \x01(\rR\x05ttlMs\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\rR\aattempt\"\x96\x01\n" +
	"\n" +
	"Completion\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\fR\aleaseId\x120\n" +
	"\x06result\x18\x02 \x01(\v2\x16.taskwire.v1.ObjectRefH\x00R\x06result\x120\n" +
	"\afailure\x18\x03 \x01(\v2\x14.taskwire.v1.FailureH\x00R\afailureB\t\n" +
	"\aoutcome\"/\n" +
	"\x12CompletionResponse\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\fR\aleaseId\"\x80\x01\n" +
	"\rForwardedTask\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\fR\n" +
	"transferId\x12\x1f\n" +
	"\vorigin_node\x18\x02 \x01(\tR\n" +
	"originNode\x12-\n" +
	"\x04task\x18\x03 \x01(\v2\x19.taskwire.v1.TaskEnvelopeR\x04task\"O\n" +
	"\x13ForwardTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\fR\x06taskId\x12\x1f\n" +
	"\vtransfer_id\x18\x02 \x01(\fR\n" +
	"transferId\"\xed\x01\n" +
	"\x13ForwardedCompletion\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\fR\n" +
	"transferId\x12\x1f\n" +
	"\vremote_node\x18\x02 \x01(\tR\n" +
	"remoteNode\x12%\n" +
	"\x0eremote_attempt\x18\x03 \x01(\rR\rremoteAttempt\x120\n" +
	"\x06result\x18\x04 \x01(\v2\x16.taskwire.v1.ObjectRefH\x00R\x06result\x120\n" +
	"\afailure\x18\x05 \x01(\v2\x14.taskwire.v1.FailureH\x00R\afailureB\t\n" +
	"\aoutcome\"<\n" +
	"\x19ForwardCompletionResponse\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\fR\n" +
	"transferId\"\x86\x01\n" +
	"\aFailure\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\adetails\x18\x03 \x01(\v2\x15.taskwire.v1.ValueRefR\adetails\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\"\xe5\x01\n" +
	"\x12ResultNotification\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\fR\aownerId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\fR\x06taskId\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x04R\x06cursor\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x120\n" +
	"\x06result\x18\x05 \x01(\v2\x16.taskwire.v1.ObjectRefH\x00R\x06result\x120\n" +
	"\afailure\x18\x06 \x01(\v2\x14.taskwire.v1.FailureH\x00R\afailureB\t\n" +
	"\aoutcome\"S\n" +
	"\x13WatchResultsRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\fR\aownerId\x12!\n" +
	"\fafter_cursor\x18\x02 \x01(\x04R\vafterCursor\"^\n" +
	"\x10AckResultRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\fR\aownerId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\fR\x06taskId\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x04R\x06cursor\"\x13\n" +
	"\x11AckResultResponse\"\x93\x04\n" +
	"\x0eStatusSnapshot\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x04R\x03pid\x12\x14\n" +
	"\x05ready\x18\x03 \x01(\bR\x05ready\x12L\n" +
	"\vtask_counts\x18\x04 \x03(\v2+.taskwire.v1.StatusSnapshot.TaskCountsEntryR\n" +
	"taskCounts\x12#\n" +
	"\ractive_leases\x18\x05 \x01(\x04R\factiveLeases\x12\x1f\n" +
	"\vworker_pids\x18\x06 \x03(\x04R\n" +
	"workerPids\x12'\n" +
	"\x0fworker_restarts\x18\a \x01(\x04R\x0eworkerRestarts\x12'\n" +
	"\x0fstorage_healthy\x18\b \x01(\bR\x0estorageHealthy\x12'\n" +
	"\x0fcluster_members\x18\t \x01(\x04R\x0eclusterMembers\x120\n" +
	"\x14kafka_outbox_pending\x18\n" +
	" \x01(\x04R\x12kafkaOutboxPending\x12+\n" +
	"\x0flast_error_code\x18\v \x01(\tH\x00R\rlastErrorCode\x88\x01\x01\x1a=\n" +
	"\x0fTaskCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01B\x12\n" +
	"\x10_last_error_code\"\xca\x01\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x129\n" +
	"\adetails\x18\x04 \x03(\v2\x1f.taskwire.v1.Error.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\fR\aleaseId\".\n" +
	"\x11HeartbeatResponse\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\fR\aleaseId\"C\n" +
	"\rCancelRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\fR\aownerId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\fR\x06taskId\"G\n" +
	"\x0eCancelResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\fR\x06taskId\x12\x1c\n" +
	"\tcancelled\x18\x02 \x01(\bR\tcancelled\"B\n" +
	"\x10ObjectGetRequest\x12.\n" +
	"\x06object\x18\x01 \x01(\v2\x16.taskwire.v1.ObjectRefR\x06object\"C\n" +
	"\x11PutObjectResponse\x12.\n" +
	"\x06object\x18\x01 \x01(\v2\x16.taskwire.v1.ObjectRefR\x06object\"c\n" +
	"\vObjectChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05codec\x18\x02 \x01(\tR\x05codec\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\fR\x06sha256\"\xc5\x01\n" +
	"\fStealRequest\x12%\n" +
	"\x0erequester_node\x18\x01 \x01(\tR\rrequesterNode\x12=\n" +
	"\x06labels\x18\x02 \x03(\v2%.taskwire.v1.StealRequest.LabelsEntryR\x06labels\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\rStealResponse\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\fR\n" +
	"transferId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\rR\baccepted\"\x0f\n" +
	"\rStatusRequest2\xfb\x06\n" +
	"\x0fTaskwireControl\x12@\n" +
	"\x06Submit\x12\x19.taskwire.v1.TaskEnvelope\x1a\x1b.taskwire.v1.SubmitResponse\x12S\n" +
	"\fWatchResults\x12 .taskwire.v1.WatchResultsRequest\x1a\x1f.taskwire.v1.ResultNotification0\x01\x12J\n" +
	"\tAckResult\x12\x1d.taskwire.v1.AckResultRequest\x1a\x1e.taskwire.v1.AckResultResponse\x12A\n" +
	"\x06Cancel\x12\x1a.taskwire.v1.CancelRequest\x1a\x1b.taskwire.v1.CancelResponse\x12?\n" +
	"\n" +
	"QueryTasks\x12\x16.taskwire.v1.TaskQuery\x1a\x19.taskwire.v1.TaskSnapshot\x12A\n" +
	"\x04Work\x12\x1a.taskwire.v1.WorkerMessage\x1a\x19.taskwire.v1.AgentMessage(\x010\x01\x12G\n" +
	"\tPutObject\x12\x18.taskwire.v1.ObjectChunk\x1a\x1e.taskwire.v1.PutObjectResponse(\x01\x12F\n" +
	"\tGetObject\x12\x1d.taskwire.v1.ObjectGetRequest\x1a\x18.taskwire.v1.ObjectChunk0\x01\x12A\n" +
	"\x06Status\x12\x1a.taskwire.v1.StatusRequest\x1a\x1b.taskwire.v1.StatusSnapshot\x12K\n" +
	"\vForwardTask\x12\x1a.taskwire.v1.ForwardedTask\x1a .taskwire.v1.ForwardTaskResponse\x12]\n" +
	"\x11ForwardCompletion\x12 .taskwire.v1.ForwardedCompletion\x1a&.taskwire.v1.ForwardCompletionResponse\x12>\n" +
	"\x05Steal\x12\x19.taskwire.v1.StealRequest\x1a\x1a.taskwire.v1.StealResponseB8Z6github.com/sanketn26/taskwire/agent/pkg/protocol/pb;pbb\x06proto3"

var (
	file_taskwire_v1_control_proto_rawDescOnce sync.Once
	file_taskwire_v1_control_proto_rawDescData []byte
)

func file_taskwire_v1_control_proto_rawDescGZIP() []byte {
	file_taskwire_v1_control_proto_rawDescOnce.Do(func() {
		file_taskwire_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taskwire_v1_control_proto_rawDesc), len(file_taskwire_v1_control_proto_rawDesc)))
	})
	return file_taskwire_v1_control_proto_rawDescData
}

var file_taskwire_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_taskwire_v1_control_proto_goTypes = []any{
	(*WorkerMessage)(nil),              // 0: taskwire.v1.WorkerMessage
	(*AgentMessage)(nil),               // 1: taskwire.v1.AgentMessage
	(*WorkerRegistration)(nil),         // 2: taskwire.v1.WorkerRegistration
	(*WorkerRegistrationResponse)(nil), // 3: taskwire.v1.WorkerRegistrationResponse
	(*ObjectRef)(nil),                  // 4: taskwire.v1.ObjectRef
	(*ValueRef)(nil),                   // 5: taskwire.v1.ValueRef
	(*PullRequest)(nil),                // 6: taskwire.v1.PullRequest
	(*TaskCapability)(nil),             // 7: taskwire.v1.TaskCapability
	(*TaskRegistration)(nil),           // 8: taskwire.v1.TaskRegistration
	(*TaskQuery)(nil),                  // 9: taskwire.v1.TaskQuery
	(*TaskSnapshotEntry)(nil),          // 10: taskwire.v1.TaskSnapshotEntry
	(*TaskSnapshot)(nil),               // 11: taskwire.v1.TaskSnapshot
	(*TaskEnvelope)(nil),               // 12: taskwire.v1.TaskEnvelope
	(*SubmitResponse)(nil),             // 13: taskwire.v1.SubmitResponse
	(*LeasedTask)(nil),                 // 14: taskwire.v1.LeasedTask
	(*Completion)(nil),                 // 15: taskwire.v1.Completion
	(*CompletionResponse)(nil),         // 16: taskwire.v1.CompletionResponse
	(*ForwardedTask)(nil),              // 17: taskwire.v1.ForwardedTask
	(*ForwardTaskResponse)(nil),        // 18: taskwire.v1.ForwardTaskResponse
	(*ForwardedCompletion)(nil),        // 19: taskwire.v1.ForwardedCompletion
	(*ForwardCompletionResponse)(nil),  // 20: taskwire.v1.ForwardCompletionResponse
	(*Failure)(nil),                    // 21: taskwire.v1.Failure
	(*ResultNotification)(nil),         // 22: taskwire.v1.ResultNotification
	(*WatchResultsRequest)(nil),        // 23: taskwire.v1.WatchResultsRequest
	(*AckResultRequest)(nil),           // 24: taskwire.v1.AckResultRequest
	(*AckResultResponse)(nil),          // 25: taskwire.v1.AckResultResponse
	(*StatusSnapshot)(nil),             // 26: taskwire.v1.StatusSnapshot
	(*Error)(nil),                      // 27: taskwire.v1.Error
	(*HeartbeatRequest)(nil),           // 28: taskwire.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),          // 29: taskwire.v1.HeartbeatResponse
	(*CancelRequest)(nil),              // 30: taskwire.v1.CancelRequest
	(*CancelResponse)(nil),             // 31: taskwire.v1.CancelResponse
	(*ObjectGetRequest)(nil),           // 32: taskwire.v1.ObjectGetRequest
	(*PutObjectResponse)(nil),          // 33: taskwire.v1.PutObjectResponse
	(*ObjectChunk)(nil),                // 34: taskwire.v1.ObjectChunk
	(*StealRequest)(nil),               // 35: taskwire.v1.StealRequest
	(*StealResponse)(nil),              // 36: taskwire.v1.StealResponse
	(*StatusRequest)(nil),              // 37: taskwire.v1.StatusRequest
	nil,                                // 38: taskwire.v1.TaskEnvelope.LabelsEntry
	nil,                                // 39: taskwire.v1.StatusSnapshot.TaskCountsEntry
	nil,                                // 40: taskwire.v1.Error.DetailsEntry
	nil,                                // 41: taskwire.v1.StealRequest.LabelsEntry
}
var file_taskwire_v1_control_proto_depIdxs = []int32{
	2,  // 0: taskwire.v1.WorkerMessage.register:type_name -> taskwire.v1.WorkerRegistration
	6,  // 1: taskwire.v1.WorkerMessage.pull:type_name -> taskwire.v1.PullRequest
	28, // 2: taskwire.v1.WorkerMessage.heartbeat:type_name -> taskwire.v1.HeartbeatRequest
	15, // 3: taskwire.v1.WorkerMessage.complete:type_name -> taskwire.v1.Completion
	8,  // 4: taskwire.v1.WorkerMessage.update_tasks:type_name -> taskwire.v1.TaskRegistration
	14, // 5: taskwire.v1.AgentMessage.task:type_name -> taskwire.v1.LeasedTask
	29, // 6: taskwire.v1.AgentMessage.heartbeat_ack:type_name -> taskwire.v1.HeartbeatResponse
	16, // 7: taskwire.v1.AgentMessage.complete_ack:type_name -> taskwire.v1.CompletionResponse
	3,  // 8: taskwire.v1.AgentMessage.registered:type_name -> taskwire.v1.WorkerRegistrationResponse
	8,  // 9: taskwire.v1.WorkerRegistration.tasks:type_name -> taskwire.v1.TaskRegistration
	4,  // 10: taskwire.v1.ValueRef.object:type_name -> taskwire.v1.ObjectRef
	7,  // 11: taskwire.v1.TaskRegistration.tasks:type_name -> taskwire.v1.TaskCapability
	4,  // 12: taskwire.v1.TaskSnapshotEntry.result:type_name -> taskwire.v1.ObjectRef
	21, // 13: taskwire.v1.TaskSnapshotEntry.failure:type_name -> taskwire.v1.Failure
	10, // 14: taskwire.v1.TaskSnapshot.tasks:type_name -> taskwire.v1.TaskSnapshotEntry
	5,  // 15: taskwire.v1.TaskEnvelope.input:type_name -> taskwire.v1.ValueRef
	38, // 16: taskwire.v1.TaskEnvelope.labels:type_name -> taskwire.v1.TaskEnvelope.LabelsEntry
	12, // 17: taskwire.v1.LeasedTask.task:type_name -> taskwire.v1.TaskEnvelope
	4,  // 18: taskwire.v1.Completion.result:type_name -> taskwire.v1.ObjectRef
	21, // 19: taskwire.v1.Completion.failure:type_name -> taskwire.v1.Failure
	12, // 20: taskwire.v1.ForwardedTask.task:type_name -> taskwire.v1.TaskEnvelope
	4,  // 21: taskwire.v1.ForwardedCompletion.result:type_name -> taskwire.v1.ObjectRef
	21, // 22: taskwire.v1.ForwardedCompletion.failure:type_name -> taskwire.v1.Failure
	5,  // 23: taskwire.v1.Failure.details:type_name -> taskwire.v1.ValueRef
	4,  // 24: taskwire.v1.ResultNotification.result:type_name -> taskwire.v1.ObjectRef
	21, // 25: taskwire.v1.ResultNotification.failure:type_name -> taskwire.v1.Failure
	39, // 26: taskwire.v1.StatusSnapshot.task_counts:type_name -> taskwire.v1.StatusSnapshot.TaskCountsEntry
	40, // 27: taskwire.v1.Error.details:type_name -> taskwire.v1.Error.DetailsEntry
	4,  // 28: taskwire.v1.ObjectGetRequest.object:type_name -> taskwire.v1.ObjectRef
	4,  // 29: taskwire.v1.PutObjectResponse.object:type_name -> taskwire.v1.ObjectRef
	41, // 30: taskwire.v1.StealRequest.labels:type_name -> taskwire.v1.StealRequest.LabelsEntry
	12, // 31: taskwire.v1.TaskwireControl.Submit:input_type -> taskwire.v1.TaskEnvelope
	23, // 32: taskwire.v1.TaskwireControl.WatchResults:input_type -> taskwire.v1.WatchResultsRequest
	24, // 33: taskwire.v1.TaskwireControl.AckResult:input_type -> taskwire.v1.AckResultRequest
	30, // 34: taskwire.v1.TaskwireControl.Cancel:input_type -> taskwire.v1.CancelRequest
	9,  // 35: taskwire.v1.TaskwireControl.QueryTasks:input_type -> taskwire.v1.TaskQuery
	0,  // 36: taskwire.v1.TaskwireControl.Work:input_type -> taskwire.v1.WorkerMessage
	34, // 37: taskwire.v1.TaskwireControl.PutObject:input_type -> taskwire.v1.ObjectChunk
	32, // 38: taskwire.v1.TaskwireControl.GetObject:input_type -> taskwire.v1.ObjectGetRequest
	37, // 39: taskwire.v1.TaskwireControl.Status:input_type -> taskwire.v1.StatusRequest
	17, // 40: taskwire.v1.TaskwireControl.ForwardTask:input_type -> taskwire.v1.ForwardedTask
	19, // 41: taskwire.v1.TaskwireControl.ForwardCompletion:input_type -> taskwire.v1.ForwardedCompletion
	35, // 42: taskwire.v1.TaskwireControl.Steal:input_type -> taskwire.v1.StealRequest
	13, // 43: taskwire.v1.TaskwireControl.Submit:output_type -> taskwire.v1.SubmitResponse
	22, // 44: taskwire.v1.TaskwireControl.WatchResults:output_type -> taskwire.v1.ResultNotification
	25, // 45: taskwire.v1.TaskwireControl.AckResult:output_type -> taskwire.v1.AckResultResponse
	31, // 46: taskwire.v1.TaskwireControl.Cancel:output_type -> taskwire.v1.CancelResponse
	11, // 47: taskwire.v1.TaskwireControl.QueryTasks:output_type -> taskwire.v1.TaskSnapshot
	1,  // 48: taskwire.v1.TaskwireControl.Work:output_type -> taskwire.v1.AgentMessage
	33, // 49: taskwire.v1.TaskwireControl.PutObject:output_type -> taskwire.v1.PutObjectResponse
	34, // 50: taskwire.v1.TaskwireControl.GetObject:output_type -> taskwire.v1.ObjectChunk
	26, // 51: taskwire.v1.TaskwireControl.Status:output_type -> taskwire.v1.StatusSnapshot
	18, // 52: taskwire.v1.TaskwireControl.ForwardTask:output_type -> taskwire.v1.ForwardTaskResponse
	20, // 53: taskwire.v1.TaskwireControl.ForwardCompletion:output_type -> taskwire.v1.ForwardCompletionResponse
	36, // 54: taskwire.v1.TaskwireControl.Steal:output_type -> taskwire.v1.StealResponse
	43, // [43:55] is the sub-list for method output_type
	31, // [31:43] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_taskwire_v1_control_proto_init() }
func file_taskwire_v1_control_proto_init() {
	if File_taskwire_v1_control_proto != nil {
		return
	}
	file_taskwire_v1_control_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Register)(nil),
		(*WorkerMessage_Pull)(nil),
		(*WorkerMessage_Heartbeat)(nil),
		(*WorkerMessage_Complete)(nil),
		(*WorkerMessage_UpdateTasks)(nil),
	}
	file_taskwire_v1_control_proto_msgTypes[1].OneofWrappers = []any{
		(*AgentMessage_Task)(nil),
		(*AgentMessage_HeartbeatAck)(nil),
		(*AgentMessage_CompleteAck)(nil),
		(*AgentMessage_Registered)(nil),
	}
	file_taskwire_v1_control_proto_msgTypes[5].OneofWrappers = []any{
		(*ValueRef_Inline)(nil),
		(*ValueRef_Object)(nil),
	}
	file_taskwire_v1_control_proto_msgTypes[10].OneofWrappers = []any{
		(*TaskSnapshotEntry_Result)(nil),
		(*TaskSnapshotEntry_Failure)(nil),
	}
	file_taskwire_v1_control_proto_msgTypes[15].OneofWrappers = []any{
		(*Completion_Result)(nil),
		(*Completion_Failure)(nil),
	}
	file_taskwire_v1_control_proto_msgTypes[19].OneofWrappers = []any{
		(*ForwardedCompletion_Result)(nil),
		(*ForwardedCompletion_Failure)(nil),
	}
	file_taskwire_v1_control_proto_msgTypes[22].OneofWrappers = []any{
		(*ResultNotification_Result)(nil),
		(*ResultNotification_Failure)(nil),
	}
	file_taskwire_v1_control_proto_msgTypes[26].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taskwire_v1_control_proto_rawDesc), len(file_taskwire_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_taskwire_v1_control_proto_goTypes,
		DependencyIndexes: file_taskwire_v1_control_proto_depIdxs,
		MessageInfos:      file_taskwire_v1_control_proto_msgTypes,
	}.Build()
	File_taskwire_v1_control_proto = out.File
	file_taskwire_v1_control_proto_goTypes = nil
	file_taskwire_v1_control_proto_depIdxs = nil
}
