// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: taskwire/v1/control.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ControlMessage is the sole protobuf payload carried by Taskwire's thin
// length-bounded frame. Task inputs and results remain opaque bytes identified
// by ValueRef.codec; "msgpack" there is an application-value codec, not the
// control-plane encoding.
type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ControlMessage_Submit
	//	*ControlMessage_ForwardedSubmit
	//	*ControlMessage_Pull
	//	*ControlMessage_Task
	//	*ControlMessage_Heartbeat
	//	*ControlMessage_Result
	//	*ControlMessage_Cancel
	//	*ControlMessage_Complete
	//	*ControlMessage_ForwardedComplete
	//	*ControlMessage_Steal
	//	*ControlMessage_Ack
	//	*ControlMessage_StatusRequest
	//	*ControlMessage_StatusSnapshot
	//	*ControlMessage_ResumeResults
	//	*ControlMessage_Error
	//	*ControlMessage_ObjectPut
	//	*ControlMessage_ObjectGet
	//	*ControlMessage_ObjectChunk
	//	*ControlMessage_Hello
	//	*ControlMessage_TaskQuery
	//	*ControlMessage_TaskSnapshot
	//	*ControlMessage_RegisterTasks
	Body          isControlMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_taskwire_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *ControlMessage) GetBody() isControlMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ControlMessage) GetSubmit() *TaskEnvelope {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_Submit); ok {
			return x.Submit
		}
	}
	return nil
}

func (x *ControlMessage) GetForwardedSubmit() *ForwardedTask {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_ForwardedSubmit); ok {
			return x.ForwardedSubmit
		}
	}
	return nil
}

func (x *ControlMessage) GetPull() *PullRequest {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_Pull); ok {
			return x.Pull
		}
	}
	return nil
}

func (x *ControlMessage) GetTask() *LeasedTask {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *ControlMessage) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ControlMessage) GetResult() *ResultNotification {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ControlMessage) GetCancel() *CancelRequest {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *ControlMessage) GetComplete() *Completion {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

func (x *ControlMessage) GetForwardedComplete() *ForwardedCompletion {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_ForwardedComplete); ok {
			return x.ForwardedComplete
		}
	}
	return nil
}

func (x *ControlMessage) GetSteal() *StealRequest {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_Steal); ok {
			return x.Steal
		}
	}
	return nil
}

func (x *ControlMessage) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ControlMessage) GetStatusRequest() *StatusRequest {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_StatusRequest); ok {
			return x.StatusRequest
		}
	}
	return nil
}

func (x *ControlMessage) GetStatusSnapshot() *StatusSnapshot {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_StatusSnapshot); ok {
			return x.StatusSnapshot
		}
	}
	return nil
}

func (x *ControlMessage) GetResumeResults() *ResumeResultsRequest {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_ResumeResults); ok {
			return x.ResumeResults
		}
	}
	return nil
}

func (x *ControlMessage) GetError() *Error {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ControlMessage) GetObjectPut() *ObjectPutRequest {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_ObjectPut); ok {
			return x.ObjectPut
		}
	}
	return nil
}

func (x *ControlMessage) GetObjectGet() *ObjectGetRequest {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_ObjectGet); ok {
			return x.ObjectGet
		}
	}
	return nil
}

func (x *ControlMessage) GetObjectChunk() *ObjectChunk {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_ObjectChunk); ok {
			return x.ObjectChunk
		}
	}
	return nil
}

func (x *ControlMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ControlMessage) GetTaskQuery() *TaskQuery {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_TaskQuery); ok {
			return x.TaskQuery
		}
	}
	return nil
}

func (x *ControlMessage) GetTaskSnapshot() *TaskSnapshot {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_TaskSnapshot); ok {
			return x.TaskSnapshot
		}
	}
	return nil
}

func (x *ControlMessage) GetRegisterTasks() *TaskRegistration {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_RegisterTasks); ok {
			return x.RegisterTasks
		}
	}
	return nil
}

type isControlMessage_Body interface {
	isControlMessage_Body()
}

type ControlMessage_Submit struct {
	Submit *TaskEnvelope `protobuf:"bytes,1,opt,name=submit,proto3,oneof"`
}

type ControlMessage_ForwardedSubmit struct {
	ForwardedSubmit *ForwardedTask `protobuf:"bytes,2,opt,name=forwarded_submit,json=forwardedSubmit,proto3,oneof"`
}

type ControlMessage_Pull struct {
	Pull *PullRequest `protobuf:"bytes,3,opt,name=pull,proto3,oneof"`
}

type ControlMessage_Task struct {
	Task *LeasedTask `protobuf:"bytes,4,opt,name=task,proto3,oneof"`
}

type ControlMessage_Heartbeat struct {
	Heartbeat *HeartbeatRequest `protobuf:"bytes,5,opt,name=heartbeat,proto3,oneof"`
}

type ControlMessage_Result struct {
	Result *ResultNotification `protobuf:"bytes,6,opt,name=result,proto3,oneof"`
}

type ControlMessage_Cancel struct {
	Cancel *CancelRequest `protobuf:"bytes,7,opt,name=cancel,proto3,oneof"`
}

type ControlMessage_Complete struct {
	Complete *Completion `protobuf:"bytes,8,opt,name=complete,proto3,oneof"`
}

type ControlMessage_ForwardedComplete struct {
	ForwardedComplete *ForwardedCompletion `protobuf:"bytes,9,opt,name=forwarded_complete,json=forwardedComplete,proto3,oneof"`
}

type ControlMessage_Steal struct {
	Steal *StealRequest `protobuf:"bytes,10,opt,name=steal,proto3,oneof"`
}

type ControlMessage_Ack struct {
	Ack *Ack `protobuf:"bytes,11,opt,name=ack,proto3,oneof"`
}

type ControlMessage_StatusRequest struct {
	StatusRequest *StatusRequest `protobuf:"bytes,12,opt,name=status_request,json=statusRequest,proto3,oneof"`
}

type ControlMessage_StatusSnapshot struct {
	StatusSnapshot *StatusSnapshot `protobuf:"bytes,13,opt,name=status_snapshot,json=statusSnapshot,proto3,oneof"`
}

type ControlMessage_ResumeResults struct {
	ResumeResults *ResumeResultsRequest `protobuf:"bytes,14,opt,name=resume_results,json=resumeResults,proto3,oneof"`
}

type ControlMessage_Error struct {
	Error *Error `protobuf:"bytes,15,opt,name=error,proto3,oneof"`
}

type ControlMessage_ObjectPut struct {
	ObjectPut *ObjectPutRequest `protobuf:"bytes,16,opt,name=object_put,json=objectPut,proto3,oneof"`
}

type ControlMessage_ObjectGet struct {
	ObjectGet *ObjectGetRequest `protobuf:"bytes,17,opt,name=object_get,json=objectGet,proto3,oneof"`
}

type ControlMessage_ObjectChunk struct {
	ObjectChunk *ObjectChunk `protobuf:"bytes,18,opt,name=object_chunk,json=objectChunk,proto3,oneof"`
}

type ControlMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,19,opt,name=hello,proto3,oneof"`
}

type ControlMessage_TaskQuery struct {
	TaskQuery *TaskQuery `protobuf:"bytes,20,opt,name=task_query,json=taskQuery,proto3,oneof"`
}

type ControlMessage_TaskSnapshot struct {
	TaskSnapshot *TaskSnapshot `protobuf:"bytes,21,opt,name=task_snapshot,json=taskSnapshot,proto3,oneof"`
}

type ControlMessage_RegisterTasks struct {
	RegisterTasks *TaskRegistration `protobuf:"bytes,22,opt,name=register_tasks,json=registerTasks,proto3,oneof"`
}

func (*ControlMessage_Submit) isControlMessage_Body() {}

func (*ControlMessage_ForwardedSubmit) isControlMessage_Body() {}

func (*ControlMessage_Pull) isControlMessage_Body() {}

func (*ControlMessage_Task) isControlMessage_Body() {}

func (*ControlMessage_Heartbeat) isControlMessage_Body() {}

func (*ControlMessage_Result) isControlMessage_Body() {}

func (*ControlMessage_Cancel) isControlMessage_Body() {}

func (*ControlMessage_Complete) isControlMessage_Body() {}

func (*ControlMessage_ForwardedComplete) isControlMessage_Body() {}

func (*ControlMessage_Steal) isControlMessage_Body() {}

func (*ControlMessage_Ack) isControlMessage_Body() {}

func (*ControlMessage_StatusRequest) isControlMessage_Body() {}

func (*ControlMessage_StatusSnapshot) isControlMessage_Body() {}

func (*ControlMessage_ResumeResults) isControlMessage_Body() {}

func (*ControlMessage_Error) isControlMessage_Body() {}

func (*ControlMessage_ObjectPut) isControlMessage_Body() {}

func (*ControlMessage_ObjectGet) isControlMessage_Body() {}

func (*ControlMessage_ObjectChunk) isControlMessage_Body() {}

func (*ControlMessage_Hello) isControlMessage_Body() {}

func (*ControlMessage_TaskQuery) isControlMessage_Body() {}

func (*ControlMessage_TaskSnapshot) isControlMessage_Body() {}

func (*ControlMessage_RegisterTasks) isControlMessage_Body() {}

type ObjectRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        []byte                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Codec         string                 `protobuf:"bytes,5,opt,name=codec,proto3" json:"codec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectRef) Reset() {
	*x = ObjectRef{}
	mi := &file_taskwire_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRef) ProtoMessage() {}

func (x *ObjectRef) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRef.ProtoReflect.Descriptor instead.
func (*ObjectRef) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectRef) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *ObjectRef) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ObjectRef) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ObjectRef) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *ObjectRef) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

type ValueRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Location:
	//
	//	*ValueRef_Inline
	//	*ValueRef_Object
	Location      isValueRef_Location `protobuf_oneof:"location"`
	Codec         string              `protobuf:"bytes,3,opt,name=codec,proto3" json:"codec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueRef) Reset() {
	*x = ValueRef{}
	mi := &file_taskwire_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueRef) ProtoMessage() {}

func (x *ValueRef) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueRef.ProtoReflect.Descriptor instead.
func (*ValueRef) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *ValueRef) GetLocation() isValueRef_Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *ValueRef) GetInline() []byte {
	if x != nil {
		if x, ok := x.Location.(*ValueRef_Inline); ok {
			return x.Inline
		}
	}
	return nil
}

func (x *ValueRef) GetObject() *ObjectRef {
	if x != nil {
		if x, ok := x.Location.(*ValueRef_Object); ok {
			return x.Object
		}
	}
	return nil
}

func (x *ValueRef) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

type isValueRef_Location interface {
	isValueRef_Location()
}

type ValueRef_Inline struct {
	Inline []byte `protobuf:"bytes,1,opt,name=inline,proto3,oneof"`
}

type ValueRef_Object struct {
	Object *ObjectRef `protobuf:"bytes,2,opt,name=object,proto3,oneof"`
}

func (*ValueRef_Inline) isValueRef_Location() {}

func (*ValueRef_Object) isValueRef_Location() {}

type Hello struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Role           string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	OwnerId        []byte                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	WorkerId       string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Runtime        string                 `protobuf:"bytes,4,opt,name=runtime,proto3" json:"runtime,omitempty"`
	RuntimeVersion string                 `protobuf:"bytes,5,opt,name=runtime_version,json=runtimeVersion,proto3" json:"runtime_version,omitempty"`
	SdkVersion     string                 `protobuf:"bytes,6,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	Codecs         []string               `protobuf:"bytes,7,rep,name=codecs,proto3" json:"codecs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_taskwire_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *Hello) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Hello) GetOwnerId() []byte {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *Hello) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Hello) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *Hello) GetRuntimeVersion() string {
	if x != nil {
		return x.RuntimeVersion
	}
	return ""
}

func (x *Hello) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *Hello) GetCodecs() []string {
	if x != nil {
		return x.Codecs
	}
	return nil
}

type PullRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WorkerId             string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CapabilityGeneration uint64                 `protobuf:"varint,2,opt,name=capability_generation,json=capabilityGeneration,proto3" json:"capability_generation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_taskwire_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *PullRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *PullRequest) GetCapabilityGeneration() uint64 {
	if x != nil {
		return x.CapabilityGeneration
	}
	return 0
}

type TaskCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskName      string                 `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	TaskVersion   string                 `protobuf:"bytes,2,opt,name=task_version,json=taskVersion,proto3" json:"task_version,omitempty"`
	Invocation    string                 `protobuf:"bytes,3,opt,name=invocation,proto3" json:"invocation,omitempty"`
	Codecs        []string               `protobuf:"bytes,4,rep,name=codecs,proto3" json:"codecs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCapability) Reset() {
	*x = TaskCapability{}
	mi := &file_taskwire_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCapability) ProtoMessage() {}

func (x *TaskCapability) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCapability.ProtoReflect.Descriptor instead.
func (*TaskCapability) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *TaskCapability) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *TaskCapability) GetTaskVersion() string {
	if x != nil {
		return x.TaskVersion
	}
	return ""
}

func (x *TaskCapability) GetInvocation() string {
	if x != nil {
		return x.Invocation
	}
	return ""
}

func (x *TaskCapability) GetCodecs() []string {
	if x != nil {
		return x.Codecs
	}
	return nil
}

type TaskRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	Tasks         []*TaskCapability      `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRegistration) Reset() {
	*x = TaskRegistration{}
	mi := &file_taskwire_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRegistration) ProtoMessage() {}

func (x *TaskRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRegistration.ProtoReflect.Descriptor instead.
func (*TaskRegistration) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *TaskRegistration) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskRegistration) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *TaskRegistration) GetTasks() []*TaskCapability {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type TaskQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       []byte                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	TaskIds       [][]byte               `protobuf:"bytes,2,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskQuery) Reset() {
	*x = TaskQuery{}
	mi := &file_taskwire_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskQuery) ProtoMessage() {}

func (x *TaskQuery) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskQuery.ProtoReflect.Descriptor instead.
func (*TaskQuery) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *TaskQuery) GetOwnerId() []byte {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *TaskQuery) GetTaskIds() [][]byte {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

type TaskSnapshotEntry struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TaskId []byte                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	State  string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Cursor *uint64                `protobuf:"varint,3,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*TaskSnapshotEntry_Result
	//	*TaskSnapshotEntry_Failure
	Outcome       isTaskSnapshotEntry_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSnapshotEntry) Reset() {
	*x = TaskSnapshotEntry{}
	mi := &file_taskwire_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSnapshotEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSnapshotEntry) ProtoMessage() {}

func (x *TaskSnapshotEntry) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSnapshotEntry.ProtoReflect.Descriptor instead.
func (*TaskSnapshotEntry) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *TaskSnapshotEntry) GetTaskId() []byte {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *TaskSnapshotEntry) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TaskSnapshotEntry) GetCursor() uint64 {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return 0
}

func (x *TaskSnapshotEntry) GetOutcome() isTaskSnapshotEntry_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *TaskSnapshotEntry) GetResult() *ObjectRef {
	if x != nil {
		if x, ok := x.Outcome.(*TaskSnapshotEntry_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *TaskSnapshotEntry) GetFailure() *Failure {
	if x != nil {
		if x, ok := x.Outcome.(*TaskSnapshotEntry_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isTaskSnapshotEntry_Outcome interface {
	isTaskSnapshotEntry_Outcome()
}

type TaskSnapshotEntry_Result struct {
	Result *ObjectRef `protobuf:"bytes,4,opt,name=result,proto3,oneof"`
}

type TaskSnapshotEntry_Failure struct {
	Failure *Failure `protobuf:"bytes,5,opt,name=failure,proto3,oneof"`
}

func (*TaskSnapshotEntry_Result) isTaskSnapshotEntry_Outcome() {}

func (*TaskSnapshotEntry_Failure) isTaskSnapshotEntry_Outcome() {}

type TaskSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskSnapshotEntry   `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSnapshot) Reset() {
	*x = TaskSnapshot{}
	mi := &file_taskwire_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSnapshot) ProtoMessage() {}

func (x *TaskSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSnapshot.ProtoReflect.Descriptor instead.
func (*TaskSnapshot) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *TaskSnapshot) GetTasks() []*TaskSnapshotEntry {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type TaskEnvelope struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OwnerId           []byte                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	TaskName          string                 `protobuf:"bytes,2,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	TaskVersion       string                 `protobuf:"bytes,3,opt,name=task_version,json=taskVersion,proto3" json:"task_version,omitempty"`
	Invocation        string                 `protobuf:"bytes,4,opt,name=invocation,proto3" json:"invocation,omitempty"`
	Input             *ValueRef              `protobuf:"bytes,5,opt,name=input,proto3" json:"input,omitempty"`
	Labels            map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Idempotent        bool                   `protobuf:"varint,7,opt,name=idempotent,proto3" json:"idempotent,omitempty"`
	SubmittedAtUnixMs int64                  `protobuf:"varint,8,opt,name=submitted_at_unix_ms,json=submittedAtUnixMs,proto3" json:"submitted_at_unix_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskEnvelope) Reset() {
	*x = TaskEnvelope{}
	mi := &file_taskwire_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEnvelope) ProtoMessage() {}

func (x *TaskEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEnvelope.ProtoReflect.Descriptor instead.
func (*TaskEnvelope) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *TaskEnvelope) GetOwnerId() []byte {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *TaskEnvelope) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *TaskEnvelope) GetTaskVersion() string {
	if x != nil {
		return x.TaskVersion
	}
	return ""
}

func (x *TaskEnvelope) GetInvocation() string {
	if x != nil {
		return x.Invocation
	}
	return ""
}

func (x *TaskEnvelope) GetInput() *ValueRef {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *TaskEnvelope) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *TaskEnvelope) GetIdempotent() bool {
	if x != nil {
		return x.Idempotent
	}
	return false
}

func (x *TaskEnvelope) GetSubmittedAtUnixMs() int64 {
	if x != nil {
		return x.SubmittedAtUnixMs
	}
	return 0
}

type LeasedTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *TaskEnvelope          `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	LeaseId       []byte                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	TtlMs         uint32                 `protobuf:"varint,3,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	Attempt       uint32                 `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeasedTask) Reset() {
	*x = LeasedTask{}
	mi := &file_taskwire_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeasedTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeasedTask) ProtoMessage() {}

func (x *LeasedTask) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeasedTask.ProtoReflect.Descriptor instead.
func (*LeasedTask) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{11}
}

func (x *LeasedTask) GetTask() *TaskEnvelope {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *LeasedTask) GetLeaseId() []byte {
	if x != nil {
		return x.LeaseId
	}
	return nil
}

func (x *LeasedTask) GetTtlMs() uint32 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

func (x *LeasedTask) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type Completion struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	LeaseId []byte                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*Completion_Result
	//	*Completion_Failure
	Outcome       isCompletion_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Completion) Reset() {
	*x = Completion{}
	mi := &file_taskwire_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Completion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Completion) ProtoMessage() {}

func (x *Completion) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Completion.ProtoReflect.Descriptor instead.
func (*Completion) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{12}
}

func (x *Completion) GetLeaseId() []byte {
	if x != nil {
		return x.LeaseId
	}
	return nil
}

func (x *Completion) GetOutcome() isCompletion_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *Completion) GetResult() *ObjectRef {
	if x != nil {
		if x, ok := x.Outcome.(*Completion_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *Completion) GetFailure() *Failure {
	if x != nil {
		if x, ok := x.Outcome.(*Completion_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isCompletion_Outcome interface {
	isCompletion_Outcome()
}

type Completion_Result struct {
	Result *ObjectRef `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type Completion_Failure struct {
	Failure *Failure `protobuf:"bytes,3,opt,name=failure,proto3,oneof"`
}

func (*Completion_Result) isCompletion_Outcome() {}

func (*Completion_Failure) isCompletion_Outcome() {}

type ForwardedTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    []byte                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	OriginNode    string                 `protobuf:"bytes,2,opt,name=origin_node,json=originNode,proto3" json:"origin_node,omitempty"`
	Task          *TaskEnvelope          `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardedTask) Reset() {
	*x = ForwardedTask{}
	mi := &file_taskwire_v1_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardedTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardedTask) ProtoMessage() {}

func (x *ForwardedTask) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardedTask.ProtoReflect.Descriptor instead.
func (*ForwardedTask) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{13}
}

func (x *ForwardedTask) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *ForwardedTask) GetOriginNode() string {
	if x != nil {
		return x.OriginNode
	}
	return ""
}

func (x *ForwardedTask) GetTask() *TaskEnvelope {
	if x != nil {
		return x.Task
	}
	return nil
}

type ForwardedCompletion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    []byte                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	RemoteNode    string                 `protobuf:"bytes,2,opt,name=remote_node,json=remoteNode,proto3" json:"remote_node,omitempty"`
	RemoteAttempt uint32                 `protobuf:"varint,3,opt,name=remote_attempt,json=remoteAttempt,proto3" json:"remote_attempt,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*ForwardedCompletion_Result
	//	*ForwardedCompletion_Failure
	Outcome       isForwardedCompletion_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardedCompletion) Reset() {
	*x = ForwardedCompletion{}
	mi := &file_taskwire_v1_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardedCompletion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardedCompletion) ProtoMessage() {}

func (x *ForwardedCompletion) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardedCompletion.ProtoReflect.Descriptor instead.
func (*ForwardedCompletion) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{14}
}

func (x *ForwardedCompletion) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *ForwardedCompletion) GetRemoteNode() string {
	if x != nil {
		return x.RemoteNode
	}
	return ""
}

func (x *ForwardedCompletion) GetRemoteAttempt() uint32 {
	if x != nil {
		return x.RemoteAttempt
	}
	return 0
}

func (x *ForwardedCompletion) GetOutcome() isForwardedCompletion_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *ForwardedCompletion) GetResult() *ObjectRef {
	if x != nil {
		if x, ok := x.Outcome.(*ForwardedCompletion_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ForwardedCompletion) GetFailure() *Failure {
	if x != nil {
		if x, ok := x.Outcome.(*ForwardedCompletion_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isForwardedCompletion_Outcome interface {
	isForwardedCompletion_Outcome()
}

type ForwardedCompletion_Result struct {
	Result *ObjectRef `protobuf:"bytes,4,opt,name=result,proto3,oneof"`
}

type ForwardedCompletion_Failure struct {
	Failure *Failure `protobuf:"bytes,5,opt,name=failure,proto3,oneof"`
}

func (*ForwardedCompletion_Result) isForwardedCompletion_Outcome() {}

func (*ForwardedCompletion_Failure) isForwardedCompletion_Outcome() {}

type Failure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       *ValueRef              `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_taskwire_v1_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{15}
}

func (x *Failure) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Failure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Failure) GetDetails() *ValueRef {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Failure) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type ResultNotification struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	OwnerId []byte                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Cursor  uint64                 `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	State   string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*ResultNotification_Result
	//	*ResultNotification_Failure
	Outcome       isResultNotification_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultNotification) Reset() {
	*x = ResultNotification{}
	mi := &file_taskwire_v1_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultNotification) ProtoMessage() {}

func (x *ResultNotification) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultNotification.ProtoReflect.Descriptor instead.
func (*ResultNotification) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{16}
}

func (x *ResultNotification) GetOwnerId() []byte {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *ResultNotification) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ResultNotification) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ResultNotification) GetOutcome() isResultNotification_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *ResultNotification) GetResult() *ObjectRef {
	if x != nil {
		if x, ok := x.Outcome.(*ResultNotification_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ResultNotification) GetFailure() *Failure {
	if x != nil {
		if x, ok := x.Outcome.(*ResultNotification_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isResultNotification_Outcome interface {
	isResultNotification_Outcome()
}

type ResultNotification_Result struct {
	Result *ObjectRef `protobuf:"bytes,4,opt,name=result,proto3,oneof"`
}

type ResultNotification_Failure struct {
	Failure *Failure `protobuf:"bytes,5,opt,name=failure,proto3,oneof"`
}

func (*ResultNotification_Result) isResultNotification_Outcome() {}

func (*ResultNotification_Failure) isResultNotification_Outcome() {}

type StatusSnapshot struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Version            string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Pid                uint64                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Ready              bool                   `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
	TaskCounts         map[string]uint64      `protobuf:"bytes,4,rep,name=task_counts,json=taskCounts,proto3" json:"task_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ActiveLeases       uint64                 `protobuf:"varint,5,opt,name=active_leases,json=activeLeases,proto3" json:"active_leases,omitempty"`
	WorkerPids         []uint64               `protobuf:"varint,6,rep,packed,name=worker_pids,json=workerPids,proto3" json:"worker_pids,omitempty"`
	WorkerRestarts     uint64                 `protobuf:"varint,7,opt,name=worker_restarts,json=workerRestarts,proto3" json:"worker_restarts,omitempty"`
	StorageHealthy     bool                   `protobuf:"varint,8,opt,name=storage_healthy,json=storageHealthy,proto3" json:"storage_healthy,omitempty"`
	ClusterMembers     uint64                 `protobuf:"varint,9,opt,name=cluster_members,json=clusterMembers,proto3" json:"cluster_members,omitempty"`
	KafkaOutboxPending uint64                 `protobuf:"varint,10,opt,name=kafka_outbox_pending,json=kafkaOutboxPending,proto3" json:"kafka_outbox_pending,omitempty"`
	LastErrorCode      *string                `protobuf:"bytes,11,opt,name=last_error_code,json=lastErrorCode,proto3,oneof" json:"last_error_code,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StatusSnapshot) Reset() {
	*x = StatusSnapshot{}
	mi := &file_taskwire_v1_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusSnapshot) ProtoMessage() {}

func (x *StatusSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusSnapshot.ProtoReflect.Descriptor instead.
func (*StatusSnapshot) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{17}
}

func (x *StatusSnapshot) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusSnapshot) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *StatusSnapshot) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *StatusSnapshot) GetTaskCounts() map[string]uint64 {
	if x != nil {
		return x.TaskCounts
	}
	return nil
}

func (x *StatusSnapshot) GetActiveLeases() uint64 {
	if x != nil {
		return x.ActiveLeases
	}
	return 0
}

func (x *StatusSnapshot) GetWorkerPids() []uint64 {
	if x != nil {
		return x.WorkerPids
	}
	return nil
}

func (x *StatusSnapshot) GetWorkerRestarts() uint64 {
	if x != nil {
		return x.WorkerRestarts
	}
	return 0
}

func (x *StatusSnapshot) GetStorageHealthy() bool {
	if x != nil {
		return x.StorageHealthy
	}
	return false
}

func (x *StatusSnapshot) GetClusterMembers() uint64 {
	if x != nil {
		return x.ClusterMembers
	}
	return 0
}

func (x *StatusSnapshot) GetKafkaOutboxPending() uint64 {
	if x != nil {
		return x.KafkaOutboxPending
	}
	return 0
}

func (x *StatusSnapshot) GetLastErrorCode() string {
	if x != nil && x.LastErrorCode != nil {
		return *x.LastErrorCode
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	TaskId        []byte                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TransferId    []byte                 `protobuf:"bytes,3,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	LeaseId       []byte                 `protobuf:"bytes,4,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	OwnerId       []byte                 `protobuf:"bytes,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Cursor        *uint64                `protobuf:"varint,6,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	Cancelled     *bool                  `protobuf:"varint,7,opt,name=cancelled,proto3,oneof" json:"cancelled,omitempty"`
	Object        *ObjectRef             `protobuf:"bytes,8,opt,name=object,proto3" json:"object,omitempty"`
	NextCursor    *uint64                `protobuf:"varint,9,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"`
	More          *bool                  `protobuf:"varint,10,opt,name=more,proto3,oneof" json:"more,omitempty"`
	Accepted      *uint32                `protobuf:"varint,11,opt,name=accepted,proto3,oneof" json:"accepted,omitempty"`
	WorkerId      string                 `protobuf:"bytes,12,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Generation    *uint64                `protobuf:"varint,13,opt,name=generation,proto3,oneof" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_taskwire_v1_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{18}
}

func (x *Ack) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Ack) GetTaskId() []byte {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *Ack) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *Ack) GetLeaseId() []byte {
	if x != nil {
		return x.LeaseId
	}
	return nil
}

func (x *Ack) GetOwnerId() []byte {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *Ack) GetCursor() uint64 {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return 0
}

func (x *Ack) GetCancelled() bool {
	if x != nil && x.Cancelled != nil {
		return *x.Cancelled
	}
	return false
}

func (x *Ack) GetObject() *ObjectRef {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *Ack) GetNextCursor() uint64 {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return 0
}

func (x *Ack) GetMore() bool {
	if x != nil && x.More != nil {
		return *x.More
	}
	return false
}

func (x *Ack) GetAccepted() uint32 {
	if x != nil && x.Accepted != nil {
		return *x.Accepted
	}
	return 0
}

func (x *Ack) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Ack) GetGeneration() uint64 {
	if x != nil && x.Generation != nil {
		return *x.Generation
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Details       map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_taskwire_v1_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{19}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *Error) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       []byte                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_taskwire_v1_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{20}
}

func (x *HeartbeatRequest) GetLeaseId() []byte {
	if x != nil {
		return x.LeaseId
	}
	return nil
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       []byte                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_taskwire_v1_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{21}
}

func (x *CancelRequest) GetOwnerId() []byte {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

type ResumeResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       []byte                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	AfterCursor   uint64                 `protobuf:"varint,2,opt,name=after_cursor,json=afterCursor,proto3" json:"after_cursor,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeResultsRequest) Reset() {
	*x = ResumeResultsRequest{}
	mi := &file_taskwire_v1_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeResultsRequest) ProtoMessage() {}

func (x *ResumeResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeResultsRequest.ProtoReflect.Descriptor instead.
func (*ResumeResultsRequest) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{22}
}

func (x *ResumeResultsRequest) GetOwnerId() []byte {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *ResumeResultsRequest) GetAfterCursor() uint64 {
	if x != nil {
		return x.AfterCursor
	}
	return 0
}

func (x *ResumeResultsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ObjectPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    []byte                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Codec         string                 `protobuf:"bytes,2,opt,name=codec,proto3" json:"codec,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        []byte                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectPutRequest) Reset() {
	*x = ObjectPutRequest{}
	mi := &file_taskwire_v1_control_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectPutRequest) ProtoMessage() {}

func (x *ObjectPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectPutRequest.ProtoReflect.Descriptor instead.
func (*ObjectPutRequest) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{23}
}

func (x *ObjectPutRequest) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *ObjectPutRequest) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *ObjectPutRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ObjectPutRequest) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

type ObjectGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    []byte                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Object        *ObjectRef             `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectGetRequest) Reset() {
	*x = ObjectGetRequest{}
	mi := &file_taskwire_v1_control_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectGetRequest) ProtoMessage() {}

func (x *ObjectGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectGetRequest.ProtoReflect.Descriptor instead.
func (*ObjectGetRequest) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{24}
}

func (x *ObjectGetRequest) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *ObjectGetRequest) GetObject() *ObjectRef {
	if x != nil {
		return x.Object
	}
	return nil
}

type ObjectChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    []byte                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Sequence      uint32                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,4,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectChunk) Reset() {
	*x = ObjectChunk{}
	mi := &file_taskwire_v1_control_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectChunk) ProtoMessage() {}

func (x *ObjectChunk) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectChunk.ProtoReflect.Descriptor instead.
func (*ObjectChunk) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{25}
}

func (x *ObjectChunk) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *ObjectChunk) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ObjectChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ObjectChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type StealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterNode string                 `protobuf:"bytes,1,opt,name=requester_node,json=requesterNode,proto3" json:"requester_node,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StealRequest) Reset() {
	*x = StealRequest{}
	mi := &file_taskwire_v1_control_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StealRequest) ProtoMessage() {}

func (x *StealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StealRequest.ProtoReflect.Descriptor instead.
func (*StealRequest) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{26}
}

func (x *StealRequest) GetRequesterNode() string {
	if x != nil {
		return x.RequesterNode
	}
	return ""
}

func (x *StealRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *StealRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_taskwire_v1_control_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskwire_v1_control_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_taskwire_v1_control_proto_rawDescGZIP(), []int{27}
}

var File_taskwire_v1_control_proto protoreflect.FileDescriptor

const file_taskwire_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x19taskwire/v1/control.proto\x12\vtaskwire.v1\"\xbb\n" +
	"\n" +
	"\x0eControlMessage\x123\n" +
	"\x06submit\x18\x01 \x01(\v2\x19.taskwire.v1.TaskEnvelopeH\x00R\x06submit\x12G\n" +
	"\x10forwarded_submit\x18\x02 \x01(\v2\x1a.taskwire.v1.ForwardedTaskH\x00R\x0fforwardedSubmit\x12.\n" +
	"\x04pull\x18\x03 \x01(\v2\x18.taskwire.v1.PullRequestH\x00R\x04pull\x12-\n" +
	"\x04task\x18\x04 \x01(\v2\x17.taskwire.v1.LeasedTaskH\x00R\x04task\x12=\n" +
	"\theartbeat\x18\x05 \x01(\v2\x1d.taskwire.v1.HeartbeatRequestH\x00R\theartbeat\x129\n" +
	"\x06result\x18\x06 \x01(\v2\x1f.taskwire.v1.ResultNotificationH\x00R\x06result\x124\n" +
	"\x06cancel\x18\a \x01(\v2\x1a.taskwire.v1.CancelRequestH\x00R\x06cancel\x125\n" +
	"\bcomplete\x18\b \x01(\v2\x17.taskwire.v1.CompletionH\x00R\bcomplete\x12Q\n" +
	"\x12forwarded_complete\x18\t \x01(\v2 .taskwire.v1.ForwardedCompletionH\x00R\x11forwardedComplete\x121\n" +
	"\x05steal\x18\n" +
	" \x01(\v2\x19.taskwire.v1.StealRequestH\x00R\x05steal\x12$\n" +
	"\x03ack\x18\v \x01(\v2\x10.taskwire.v1.AckH\x00R\x03ack\x12C\n" +
	"\x0estatus_request\x18\f \x01(\v2\x1a.taskwire.v1.StatusRequestH\x00R\rstatusRequest\x12F\n" +
	"\x0fstatus_snapshot\x18\r \x01(\v2\x1b.taskwire.v1.StatusSnapshotH\x00R\x0estatusSnapshot\x12J\n" +
	"\x0eresume_results\x18\x0e \x01(\v2!.taskwire.v1.ResumeResultsRequestH\x00R\rresumeResults\x12*\n" +
	"\x05error\x18\x0f \x01(\v2\x12.taskwire.v1.ErrorH\x00R\x05error\x12>\n" +
	"\n" +
	"object_put\x18\x10 \x01(\v2\x1d.taskwire.v1.ObjectPutRequestH\x00R\tobjectPut\x12>\n" +
	"\n" +
	"object_get\x18\x11 \x01(\v2\x1d.taskwire.v1.ObjectGetRequestH\x00R\tobjectGet\x12=\n" +
	"\fobject_chunk\x18\x12 \x01(\v2\x18.taskwire.v1.ObjectChunkH\x00R\vobjectChunk\x12*\n" +
	"\x05hello\x18\x13 \x01(\v2\x12.taskwire.v1.HelloH\x00R\x05hello\x127\n" +
	"\n" +
	"task_query\x18\x14 \x01(\v2\x16.taskwire.v1.TaskQueryH\x00R\ttaskQuery\x12@\n" +
	"\rtask_snapshot\x18\x15 \x01(\v2\x19.taskwire.v1.TaskSnapshotH\x00R\ftaskSnapshot\x12F\n" +
	"\x0eregister_tasks\x18\x16 \x01(\v2\x1d.taskwire.v1.TaskRegistrationH\x00R\rregisterTasksB\x06\n" +
	"\x04body\"u\n" +
	"\tObjectRef\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\fR\x06sha256\x12\x14\n" +
	"\x05codec\x18\x05 \x01(\tR\x05codec\"x\n" +
	"\bValueRef\x12\x18\n" +
	"\x06inline\x18\x01 \x01(\fH\x00R\x06inline\x120\n" +
	"\x06object\x18\x02 \x01(\v2\x16.taskwire.v1.ObjectRefH\x00R\x06object\x12\x14\n" +
	"\x05codec\x18\x03 \x01(\tR\x05codecB\n" +
	"\n" +
	"\blocation\"\xcf\x01\n" +
	"\x05Hello\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\fR\aownerId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12\x18\n" +
	"\aruntime\x18\x04 \x01(\tR\aruntime\x12'\n" +
	"\x0fruntime_version\x18\x05 \x01(\tR\x0eruntimeVersion\x12\x1f\n" +
	"\vsdk_version\x18\x06 \x01(\tR\n" +
	"sdkVersion\x12\x16\n" +
	"\x06codecs\x18\a \x03(\tR\x06codecs\"_\n" +
	"\vPullRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x123\n" +
	"\x15capability_generation\x18\x02 \x01(\x04R\x14capabilityGeneration\"\x88\x01\n" +
	"\x0eTaskCapability\x12\x1b\n" +
	"\ttask_name\x18\x01 \x01(\tR\btaskName\x12!\n" +
	"\ftask_version\x18\x02 \x01(\tR\vtaskVersion\x12\x1e\n" +
	"\n" +
	"invocation\x18\x03 \x01(\tR\n" +
	"invocation\x12\x16\n" +
	"\x06codecs\x18\x04 \x03(\tR\x06codecs\"\x82\x01\n" +
	"\x10TaskRegistration\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x121\n" +
	"\x05tasks\x18\x03 \x03(\v2\x1b.taskwire.v1.TaskCapabilityR\x05tasks\"A\n" +
	"\tTaskQuery\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\fR\aownerId\x12\x19\n" +
	"\btask_ids\x18\x02 \x03(\fR\ataskIds\"\xd9\x01\n" +
	"\x11TaskSnapshotEntry\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\fR\x06taskId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1b\n" +
	"\x06cursor\x18\x03 \x01(\x04H\x01R\x06cursor\x88\x01\x01\x120\n" +
	"\x06result\x18\x04 \x01(\v2\x16.taskwire.v1.ObjectRefH\x00R\x06result\x120\n" +
	"\afailure\x18\x05 \x01(\v2\x14.taskwire.v1.FailureH\x00R\afailureB\t\n" +
	"\aoutcomeB\t\n" +
	"\a_cursor\"D\n" +
	"\fTaskSnapshot\x124\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1e.taskwire.v1.TaskSnapshotEntryR\x05tasks\"\x81\x03\n" +
	"\fTaskEnvelope\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\fR\aownerId\x12\x1b\n" +
	"\ttask_name\x18\x02 \x01(\tR\btaskName\x12!\n" +
	"\ftask_version\x18\x03 \x01(\tR\vtaskVersion\x12\x1e\n" +
	"\n" +
	"invocation\x18\x04 \x01(\tR\n" +
	"invocation\x12+\n" +
	"\x05input\x18\x05 \x01(\v2\x15.taskwire.v1.ValueRefR\x05input\x12=\n" +
	"\x06labels\x18\x06 \x03(\v2%.taskwire.v1.TaskEnvelope.LabelsEntryR\x06labels\x12\x1e\n" +
	"\n" +
	"idempotent\x18\a \x01(\bR\n" +
	"idempotent\x12/\n" +
	"\x14submitted_at_unix_ms\x18\b \x01(\x03R\x11submittedAtUnixMs\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x01\n" +
	"\n" +
	"LeasedTask\x12-\n" +
	"\x04task\x18\x01 \x01(\v2\x19.taskwire.v1.TaskEnvelopeR\x04task\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\fR\aleaseId\x12\x15\n" +
	"\x06ttl_ms\x18\x03 \x01(\rR\x05ttlMs\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\rR\aattempt\"\x96\x01\n" +
	"\n" +
	"Completion\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\fR\aleaseId\x120\n" +
	"\x06result\x18\x02 \x01(\v2\x16.taskwire.v1.ObjectRefH\x00R\x06result\x120\n" +
	"\afailure\x18\x03 \x01(\v2\x14.taskwire.v1.FailureH\x00R\afailureB\t\n" +
	"\aoutcome\"\x80\x01\n" +
	"\rForwardedTask\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\fR\n" +
	"transferId\x12\x1f\n" +
	"\vorigin_node\x18\x02 \x01(\tR\n" +
	"originNode\x12-\n" +
	"\x04task\x18\x03 \x01(\v2\x19.taskwire.v1.TaskEnvelopeR\x04task\"\xed\x01\n" +
	"\x13ForwardedCompletion\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\fR\n" +
	"transferId\x12\x1f\n" +
	"\vremote_node\x18\x02 \x01(\tR\n" +
	"remoteNode\x12%\n" +
	"\x0eremote_attempt\x18\x03 \x01(\rR\rremoteAttempt\x120\n" +
	"\x06result\x18\x04 \x01(\v2\x16.taskwire.v1.ObjectRefH\x00R\x06result\x120\n" +
	"\afailure\x18\x05 \x01(\v2\x14.taskwire.v1.FailureH\x00R\afailureB\t\n" +
	"\aoutcome\"\x86\x01\n" +
	"\aFailure\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\adetails\x18\x03 \x01(\v2\x15.taskwire.v1.ValueRefR\adetails\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\"\xcc\x01\n" +
	"\x12ResultNotification\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\fR\aownerId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x04R\x06cursor\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x120\n" +
	"\x06result\x18\x04 \x01(\v2\x16.taskwire.v1.ObjectRefH\x00R\x06result\x120\n" +
	"\afailure\x18\x05 \x01(\v2\x14.taskwire.v1.FailureH\x00R\afailureB\t\n" +
	"\aoutcome\"\x93\x04\n" +
	"\x0eStatusSnapshot\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x04R\x03pid\x12\x14\n" +
	"\x05ready\x18\x03 \x01(\bR\x05ready\x12L\n" +
	"\vtask_counts\x18\x04 \x03(\v2+.taskwire.v1.StatusSnapshot.TaskCountsEntryR\n" +
	"taskCounts\x12#\n" +
	"\ractive_leases\x18\x05 \x01(\x04R\factiveLeases\x12\x1f\n" +
	"\vworker_pids\x18\x06 \x03(\x04R\n" +
	"workerPids\x12'\n" +
	"\x0fworker_restarts\x18\a \x01(\x04R\x0eworkerRestarts\x12'\n" +
	"\x0fstorage_healthy\x18\b \x01(\bR\x0estorageHealthy\x12'\n" +
	"\x0fcluster_members\x18\t \x01(\x04R\x0eclusterMembers\x120\n" +
	"\x14kafka_outbox_pending\x18\n" +
	" \x01(\x04R\x12kafkaOutboxPending\x12+\n" +
	"\x0flast_error_code\x18\v \x01(\tH\x00R\rlastErrorCode\x88\x01\x01\x1a=\n" +
	"\x0fTaskCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01B\x12\n" +
	"\x10_last_error_code\"\xe9\x03\n" +
	"\x03Ack\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\fR\x06taskId\x12\x1f\n" +
	"\vtransfer_id\x18\x03 \x01(\fR\n" +
	"transferId\x12\x19\n" +
	"\blease_id\x18\x04 \x01(\fR\aleaseId\x12\x19\n" +
	"\bowner_id\x18\x05 \x01(\fR\aownerId\x12\x1b\n" +
	"\x06cursor\x18\x06 \x01(\x04H\x00R\x06cursor\x88\x01\x01\x12!\n" +
	"\tcancelled\x18\a \x01(\bH\x01R\tcancelled\x88\x01\x01\x12.\n" +
	"\x06object\x18\b \x01(\v2\x16.taskwire.v1.ObjectRefR\x06object\x12$\n" +
	"\vnext_cursor\x18\t \x01(\x04H\x02R\n" +
	"nextCursor\x88\x01\x01\x12\x17\n" +
	"\x04more\x18\n" +
	" \x01(\bH\x03R\x04more\x88\x01\x01\x12\x1f\n" +
	"\baccepted\x18\v \x01(\rH\x04R\baccepted\x88\x01\x01\x12\x1b\n" +
	"\tworker_id\x18\f \x01(\tR\bworkerId\x12#\n" +
	"\n" +
	"generation\x18\r \x01(\x04H\x05R\n" +
	"generation\x88\x01\x01B\t\n" +
	"\a_cursorB\f\n" +
	"\n" +
	"_cancelledB\x0e\n" +
	"\f_next_cursorB\a\n" +
	"\x05_moreB\v\n" +
	"\t_acceptedB\r\n" +
	"\v_generation\"\xca\x01\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x129\n" +
	"\adetails\x18\x04 \x03(\v2\x1f.taskwire.v1.Error.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\fR\aleaseId\"*\n" +
	"\rCancelRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\fR\aownerId\"j\n" +
	"\x14ResumeResultsRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\fR\aownerId\x12!\n" +
	"\fafter_cursor\x18\x02 \x01(\x04R\vafterCursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"u\n" +
	"\x10ObjectPutRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\fR\n" +
	"transferId\x12\x14\n" +
	"\x05codec\x18\x02 \x01(\tR\x05codec\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\fR\x06sha256\"c\n" +
	"\x10ObjectGetRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\fR\n" +
	"transferId\x12.\n" +
	"\x06object\x18\x02 \x01(\v2\x16.taskwire.v1.ObjectRefR\x06object\"p\n" +
	"\vObjectChunk\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\fR\n" +
	"transferId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\rR\bsequence\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x04 \x01(\bR\x03eof\"\xc5\x01\n" +
	"\fStealRequest\x12%\n" +
	"\x0erequester_node\x18\x01 \x01(\tR\rrequesterNode\x12=\n" +
	"\x06labels\x18\x02 \x03(\v2%.taskwire.v1.StealRequest.LabelsEntryR\x06labels\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0f\n" +
	"\rStatusRequestB8Z6github.com/sanketn26/taskwire/agent/pkg/protocol/pb;pbb\x06proto3"

var (
	file_taskwire_v1_control_proto_rawDescOnce sync.Once
	file_taskwire_v1_control_proto_rawDescData []byte
)

func file_taskwire_v1_control_proto_rawDescGZIP() []byte {
	file_taskwire_v1_control_proto_rawDescOnce.Do(func() {
		file_taskwire_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taskwire_v1_control_proto_rawDesc), len(file_taskwire_v1_control_proto_rawDesc)))
	})
	return file_taskwire_v1_control_proto_rawDescData
}

var file_taskwire_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_taskwire_v1_control_proto_goTypes = []any{
	(*ControlMessage)(nil),       // 0: taskwire.v1.ControlMessage
	(*ObjectRef)(nil),            // 1: taskwire.v1.ObjectRef
	(*ValueRef)(nil),             // 2: taskwire.v1.ValueRef
	(*Hello)(nil),                // 3: taskwire.v1.Hello
	(*PullRequest)(nil),          // 4: taskwire.v1.PullRequest
	(*TaskCapability)(nil),       // 5: taskwire.v1.TaskCapability
	(*TaskRegistration)(nil),     // 6: taskwire.v1.TaskRegistration
	(*TaskQuery)(nil),            // 7: taskwire.v1.TaskQuery
	(*TaskSnapshotEntry)(nil),    // 8: taskwire.v1.TaskSnapshotEntry
	(*TaskSnapshot)(nil),         // 9: taskwire.v1.TaskSnapshot
	(*TaskEnvelope)(nil),         // 10: taskwire.v1.TaskEnvelope
	(*LeasedTask)(nil),           // 11: taskwire.v1.LeasedTask
	(*Completion)(nil),           // 12: taskwire.v1.Completion
	(*ForwardedTask)(nil),        // 13: taskwire.v1.ForwardedTask
	(*ForwardedCompletion)(nil),  // 14: taskwire.v1.ForwardedCompletion
	(*Failure)(nil),              // 15: taskwire.v1.Failure
	(*ResultNotification)(nil),   // 16: taskwire.v1.ResultNotification
	(*StatusSnapshot)(nil),       // 17: taskwire.v1.StatusSnapshot
	(*Ack)(nil),                  // 18: taskwire.v1.Ack
	(*Error)(nil),                // 19: taskwire.v1.Error
	(*HeartbeatRequest)(nil),     // 20: taskwire.v1.HeartbeatRequest
	(*CancelRequest)(nil),        // 21: taskwire.v1.CancelRequest
	(*ResumeResultsRequest)(nil), // 22: taskwire.v1.ResumeResultsRequest
	(*ObjectPutRequest)(nil),     // 23: taskwire.v1.ObjectPutRequest
	(*ObjectGetRequest)(nil),     // 24: taskwire.v1.ObjectGetRequest
	(*ObjectChunk)(nil),          // 25: taskwire.v1.ObjectChunk
	(*StealRequest)(nil),         // 26: taskwire.v1.StealRequest
	(*StatusRequest)(nil),        // 27: taskwire.v1.StatusRequest
	nil,                          // 28: taskwire.v1.TaskEnvelope.LabelsEntry
	nil,                          // 29: taskwire.v1.StatusSnapshot.TaskCountsEntry
	nil,                          // 30: taskwire.v1.Error.DetailsEntry
	nil,                          // 31: taskwire.v1.StealRequest.LabelsEntry
}
var file_taskwire_v1_control_proto_depIdxs = []int32{
	10, // 0: taskwire.v1.ControlMessage.submit:type_name -> taskwire.v1.TaskEnvelope
	13, // 1: taskwire.v1.ControlMessage.forwarded_submit:type_name -> taskwire.v1.ForwardedTask
	4,  // 2: taskwire.v1.ControlMessage.pull:type_name -> taskwire.v1.PullRequest
	11, // 3: taskwire.v1.ControlMessage.task:type_name -> taskwire.v1.LeasedTask
	20, // 4: taskwire.v1.ControlMessage.heartbeat:type_name -> taskwire.v1.HeartbeatRequest
	16, // 5: taskwire.v1.ControlMessage.result:type_name -> taskwire.v1.ResultNotification
	21, // 6: taskwire.v1.ControlMessage.cancel:type_name -> taskwire.v1.CancelRequest
	12, // 7: taskwire.v1.ControlMessage.complete:type_name -> taskwire.v1.Completion
	14, // 8: taskwire.v1.ControlMessage.forwarded_complete:type_name -> taskwire.v1.ForwardedCompletion
	26, // 9: taskwire.v1.ControlMessage.steal:type_name -> taskwire.v1.StealRequest
	18, // 10: taskwire.v1.ControlMessage.ack:type_name -> taskwire.v1.Ack
	27, // 11: taskwire.v1.ControlMessage.status_request:type_name -> taskwire.v1.StatusRequest
	17, // 12: taskwire.v1.ControlMessage.status_snapshot:type_name -> taskwire.v1.StatusSnapshot
	22, // 13: taskwire.v1.ControlMessage.resume_results:type_name -> taskwire.v1.ResumeResultsRequest
	19, // 14: taskwire.v1.ControlMessage.error:type_name -> taskwire.v1.Error
	23, // 15: taskwire.v1.ControlMessage.object_put:type_name -> taskwire.v1.ObjectPutRequest
	24, // 16: taskwire.v1.ControlMessage.object_get:type_name -> taskwire.v1.ObjectGetRequest
	25, // 17: taskwire.v1.ControlMessage.object_chunk:type_name -> taskwire.v1.ObjectChunk
	3,  // 18: taskwire.v1.ControlMessage.hello:type_name -> taskwire.v1.Hello
	7,  // 19: taskwire.v1.ControlMessage.task_query:type_name -> taskwire.v1.TaskQuery
	9,  // 20: taskwire.v1.ControlMessage.task_snapshot:type_name -> taskwire.v1.TaskSnapshot
	6,  // 21: taskwire.v1.ControlMessage.register_tasks:type_name -> taskwire.v1.TaskRegistration
	1,  // 22: taskwire.v1.ValueRef.object:type_name -> taskwire.v1.ObjectRef
	5,  // 23: taskwire.v1.TaskRegistration.tasks:type_name -> taskwire.v1.TaskCapability
	1,  // 24: taskwire.v1.TaskSnapshotEntry.result:type_name -> taskwire.v1.ObjectRef
	15, // 25: taskwire.v1.TaskSnapshotEntry.failure:type_name -> taskwire.v1.Failure
	8,  // 26: taskwire.v1.TaskSnapshot.tasks:type_name -> taskwire.v1.TaskSnapshotEntry
	2,  // 27: taskwire.v1.TaskEnvelope.input:type_name -> taskwire.v1.ValueRef
	28, // 28: taskwire.v1.TaskEnvelope.labels:type_name -> taskwire.v1.TaskEnvelope.LabelsEntry
	10, // 29: taskwire.v1.LeasedTask.task:type_name -> taskwire.v1.TaskEnvelope
	1,  // 30: taskwire.v1.Completion.result:type_name -> taskwire.v1.ObjectRef
	15, // 31: taskwire.v1.Completion.failure:type_name -> taskwire.v1.Failure
	10, // 32: taskwire.v1.ForwardedTask.task:type_name -> taskwire.v1.TaskEnvelope
	1,  // 33: taskwire.v1.ForwardedCompletion.result:type_name -> taskwire.v1.ObjectRef
	15, // 34: taskwire.v1.ForwardedCompletion.failure:type_name -> taskwire.v1.Failure
	2,  // 35: taskwire.v1.Failure.details:type_name -> taskwire.v1.ValueRef
	1,  // 36: taskwire.v1.ResultNotification.result:type_name -> taskwire.v1.ObjectRef
	15, // 37: taskwire.v1.ResultNotification.failure:type_name -> taskwire.v1.Failure
	29, // 38: taskwire.v1.StatusSnapshot.task_counts:type_name -> taskwire.v1.StatusSnapshot.TaskCountsEntry
	1,  // 39: taskwire.v1.Ack.object:type_name -> taskwire.v1.ObjectRef
	30, // 40: taskwire.v1.Error.details:type_name -> taskwire.v1.Error.DetailsEntry
	1,  // 41: taskwire.v1.ObjectGetRequest.object:type_name -> taskwire.v1.ObjectRef
	31, // 42: taskwire.v1.StealRequest.labels:type_name -> taskwire.v1.StealRequest.LabelsEntry
	43, // [43:43] is the sub-list for method output_type
	43, // [43:43] is the sub-list for method input_type
	43, // [43:43] is the sub-list for extension type_name
	43, // [43:43] is the sub-list for extension extendee
	0,  // [0:43] is the sub-list for field type_name
}

func init() { file_taskwire_v1_control_proto_init() }
func file_taskwire_v1_control_proto_init() {
	if File_taskwire_v1_control_proto != nil {
		return
	}
	file_taskwire_v1_control_proto_msgTypes[0].OneofWrappers = []any{
		(*ControlMessage_Submit)(nil),
		(*ControlMessage_ForwardedSubmit)(nil),
		(*ControlMessage_Pull)(nil),
		(*ControlMessage_Task)(nil),
		(*ControlMessage_Heartbeat)(nil),
		(*ControlMessage_Result)(nil),
		(*ControlMessage_Cancel)(nil),
		(*ControlMessage_Complete)(nil),
		(*ControlMessage_ForwardedComplete)(nil),
		(*ControlMessage_Steal)(nil),
		(*ControlMessage_Ack)(nil),
		(*ControlMessage_StatusRequest)(nil),
		(*ControlMessage_StatusSnapshot)(nil),
		(*ControlMessage_ResumeResults)(nil),
		(*ControlMessage_Error)(nil),
		(*ControlMessage_ObjectPut)(nil),
		(*ControlMessage_ObjectGet)(nil),
		(*ControlMessage_ObjectChunk)(nil),
		(*ControlMessage_Hello)(nil),
		(*ControlMessage_TaskQuery)(nil),
		(*ControlMessage_TaskSnapshot)(nil),
		(*ControlMessage_RegisterTasks)(nil),
	}
	file_taskwire_v1_control_proto_msgTypes[2].OneofWrappers = []any{
		(*ValueRef_Inline)(nil),
		(*ValueRef_Object)(nil),
	}
	file_taskwire_v1_control_proto_msgTypes[8].OneofWrappers = []any{
		(*TaskSnapshotEntry_Result)(nil),
		(*TaskSnapshotEntry_Failure)(nil),
	}
	file_taskwire_v1_control_proto_msgTypes[12].OneofWrappers = []any{
		(*Completion_Result)(nil),
		(*Completion_Failure)(nil),
	}
	file_taskwire_v1_control_proto_msgTypes[14].OneofWrappers = []any{
		(*ForwardedCompletion_Result)(nil),
		(*ForwardedCompletion_Failure)(nil),
	}
	file_taskwire_v1_control_proto_msgTypes[16].OneofWrappers = []any{
		(*ResultNotification_Result)(nil),
		(*ResultNotification_Failure)(nil),
	}
	file_taskwire_v1_control_proto_msgTypes[17].OneofWrappers = []any{}
	file_taskwire_v1_control_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taskwire_v1_control_proto_rawDesc), len(file_taskwire_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_taskwire_v1_control_proto_goTypes,
		DependencyIndexes: file_taskwire_v1_control_proto_depIdxs,
		MessageInfos:      file_taskwire_v1_control_proto_msgTypes,
	}.Build()
	File_taskwire_v1_control_proto = out.File
	file_taskwire_v1_control_proto_goTypes = nil
	file_taskwire_v1_control_proto_depIdxs = nil
}
