// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: taskwire/v1/control.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskwireControl_Submit_FullMethodName            = "/taskwire.v1.TaskwireControl/Submit"
	TaskwireControl_WatchResults_FullMethodName      = "/taskwire.v1.TaskwireControl/WatchResults"
	TaskwireControl_AckResult_FullMethodName         = "/taskwire.v1.TaskwireControl/AckResult"
	TaskwireControl_Cancel_FullMethodName            = "/taskwire.v1.TaskwireControl/Cancel"
	TaskwireControl_QueryTasks_FullMethodName        = "/taskwire.v1.TaskwireControl/QueryTasks"
	TaskwireControl_RegisterTasks_FullMethodName     = "/taskwire.v1.TaskwireControl/RegisterTasks"
	TaskwireControl_Work_FullMethodName              = "/taskwire.v1.TaskwireControl/Work"
	TaskwireControl_PutObject_FullMethodName         = "/taskwire.v1.TaskwireControl/PutObject"
	TaskwireControl_GetObject_FullMethodName         = "/taskwire.v1.TaskwireControl/GetObject"
	TaskwireControl_Status_FullMethodName            = "/taskwire.v1.TaskwireControl/Status"
	TaskwireControl_ForwardTask_FullMethodName       = "/taskwire.v1.TaskwireControl/ForwardTask"
	TaskwireControl_ForwardCompletion_FullMethodName = "/taskwire.v1.TaskwireControl/ForwardCompletion"
	TaskwireControl_Steal_FullMethodName             = "/taskwire.v1.TaskwireControl/Steal"
)

// TaskwireControlClient is the client API for TaskwireControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TaskwireControl is the authoritative control-plane contract. gRPC over
// HTTP/2 supplies framing, request correlation, deadlines, flow control, and
// cancellation; Taskwire defines only the messages and their semantics.
//
// Task inputs and results remain opaque bytes identified by ValueRef.codec;
// "msgpack" there is an application-value codec, not the control-plane
// encoding.
//
// Roles (runtime, worker, admin) are carried in per-RPC metadata rather than a
// HELLO handshake message; see docs/protocol.md. Errors use gRPC status codes
// with a Taskwire stable error code in the status details.
type TaskwireControlClient interface {
	// Submit enqueues one task. The response is sent only after the input and
	// task-state durability boundary, preserving the durable submit ACK.
	Submit(ctx context.Context, in *TaskEnvelope, opts ...grpc.CallOption) (*SubmitResponse, error)
	// WatchResults streams terminal result notifications for one owner,
	// resuming after the supplied cursor. Replaces RESUME_RESULTS plus
	// unsolicited RESULT frames: stream position is the cursor, so a
	// reconnecting Runtime replays by reopening the stream.
	WatchResults(ctx context.Context, in *WatchResultsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResultNotification], error)
	// AckResult confirms durable client-side handling of one notification so
	// the agent may release it before retention expiry.
	AckResult(ctx context.Context, in *AckResultRequest, opts ...grpc.CallOption) (*AckResultResponse, error)
	// Cancel requests cancellation of an owner's task.
	Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
	// QueryTasks returns owner-isolated task snapshots.
	QueryTasks(ctx context.Context, in *TaskQuery, opts ...grpc.CallOption) (*TaskSnapshot, error)
	// RegisterTasks atomically replaces the connection's task capability set.
	RegisterTasks(ctx context.Context, in *TaskRegistration, opts ...grpc.CallOption) (*RegisterTasksResponse, error)
	// Work is the worker's long-lived duplex session. The worker sends its
	// registration, pull requests, heartbeats, and completions; the agent
	// sends leased tasks. Stream lifetime bounds lease ownership, so a
	// dropped connection is an unambiguous signal to reap leases.
	Work(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, AgentMessage], error)
	// PutObject streams object content; the response carries the canonical
	// ObjectRef after size/checksum verification and the durability boundary.
	PutObject(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ObjectChunk, PutObjectResponse], error)
	// GetObject streams stored object content.
	GetObject(ctx context.Context, in *ObjectGetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ObjectChunk], error)
	// Status returns an agent status snapshot. Also serves as the readiness
	// probe used by the CLI and test harness.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusSnapshot, error)
	// ForwardTask transfers a task to a peer agent (cluster, Phase 5).
	ForwardTask(ctx context.Context, in *ForwardedTask, opts ...grpc.CallOption) (*ForwardTaskResponse, error)
	// ForwardCompletion returns a remote completion to the origin agent.
	ForwardCompletion(ctx context.Context, in *ForwardedCompletion, opts ...grpc.CallOption) (*ForwardCompletionResponse, error)
	// Steal requests work from a peer agent (cluster, Phase 5).
	Steal(ctx context.Context, in *StealRequest, opts ...grpc.CallOption) (*StealResponse, error)
}

type taskwireControlClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskwireControlClient(cc grpc.ClientConnInterface) TaskwireControlClient {
	return &taskwireControlClient{cc}
}

func (c *taskwireControlClient) Submit(ctx context.Context, in *TaskEnvelope, opts ...grpc.CallOption) (*SubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, TaskwireControl_Submit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskwireControlClient) WatchResults(ctx context.Context, in *WatchResultsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResultNotification], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskwireControl_ServiceDesc.Streams[0], TaskwireControl_WatchResults_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchResultsRequest, ResultNotification]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskwireControl_WatchResultsClient = grpc.ServerStreamingClient[ResultNotification]

func (c *taskwireControlClient) AckResult(ctx context.Context, in *AckResultRequest, opts ...grpc.CallOption) (*AckResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResultResponse)
	err := c.cc.Invoke(ctx, TaskwireControl_AckResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskwireControlClient) Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, TaskwireControl_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskwireControlClient) QueryTasks(ctx context.Context, in *TaskQuery, opts ...grpc.CallOption) (*TaskSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskSnapshot)
	err := c.cc.Invoke(ctx, TaskwireControl_QueryTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskwireControlClient) RegisterTasks(ctx context.Context, in *TaskRegistration, opts ...grpc.CallOption) (*RegisterTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterTasksResponse)
	err := c.cc.Invoke(ctx, TaskwireControl_RegisterTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskwireControlClient) Work(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, AgentMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskwireControl_ServiceDesc.Streams[1], TaskwireControl_Work_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerMessage, AgentMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskwireControl_WorkClient = grpc.BidiStreamingClient[WorkerMessage, AgentMessage]

func (c *taskwireControlClient) PutObject(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ObjectChunk, PutObjectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskwireControl_ServiceDesc.Streams[2], TaskwireControl_PutObject_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ObjectChunk, PutObjectResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskwireControl_PutObjectClient = grpc.ClientStreamingClient[ObjectChunk, PutObjectResponse]

func (c *taskwireControlClient) GetObject(ctx context.Context, in *ObjectGetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ObjectChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskwireControl_ServiceDesc.Streams[3], TaskwireControl_GetObject_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ObjectGetRequest, ObjectChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskwireControl_GetObjectClient = grpc.ServerStreamingClient[ObjectChunk]

func (c *taskwireControlClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusSnapshot)
	err := c.cc.Invoke(ctx, TaskwireControl_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskwireControlClient) ForwardTask(ctx context.Context, in *ForwardedTask, opts ...grpc.CallOption) (*ForwardTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardTaskResponse)
	err := c.cc.Invoke(ctx, TaskwireControl_ForwardTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskwireControlClient) ForwardCompletion(ctx context.Context, in *ForwardedCompletion, opts ...grpc.CallOption) (*ForwardCompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardCompletionResponse)
	err := c.cc.Invoke(ctx, TaskwireControl_ForwardCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskwireControlClient) Steal(ctx context.Context, in *StealRequest, opts ...grpc.CallOption) (*StealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StealResponse)
	err := c.cc.Invoke(ctx, TaskwireControl_Steal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskwireControlServer is the server API for TaskwireControl service.
// All implementations must embed UnimplementedTaskwireControlServer
// for forward compatibility.
//
// TaskwireControl is the authoritative control-plane contract. gRPC over
// HTTP/2 supplies framing, request correlation, deadlines, flow control, and
// cancellation; Taskwire defines only the messages and their semantics.
//
// Task inputs and results remain opaque bytes identified by ValueRef.codec;
// "msgpack" there is an application-value codec, not the control-plane
// encoding.
//
// Roles (runtime, worker, admin) are carried in per-RPC metadata rather than a
// HELLO handshake message; see docs/protocol.md. Errors use gRPC status codes
// with a Taskwire stable error code in the status details.
type TaskwireControlServer interface {
	// Submit enqueues one task. The response is sent only after the input and
	// task-state durability boundary, preserving the durable submit ACK.
	Submit(context.Context, *TaskEnvelope) (*SubmitResponse, error)
	// WatchResults streams terminal result notifications for one owner,
	// resuming after the supplied cursor. Replaces RESUME_RESULTS plus
	// unsolicited RESULT frames: stream position is the cursor, so a
	// reconnecting Runtime replays by reopening the stream.
	WatchResults(*WatchResultsRequest, grpc.ServerStreamingServer[ResultNotification]) error
	// AckResult confirms durable client-side handling of one notification so
	// the agent may release it before retention expiry.
	AckResult(context.Context, *AckResultRequest) (*AckResultResponse, error)
	// Cancel requests cancellation of an owner's task.
	Cancel(context.Context, *CancelRequest) (*CancelResponse, error)
	// QueryTasks returns owner-isolated task snapshots.
	QueryTasks(context.Context, *TaskQuery) (*TaskSnapshot, error)
	// RegisterTasks atomically replaces the connection's task capability set.
	RegisterTasks(context.Context, *TaskRegistration) (*RegisterTasksResponse, error)
	// Work is the worker's long-lived duplex session. The worker sends its
	// registration, pull requests, heartbeats, and completions; the agent
	// sends leased tasks. Stream lifetime bounds lease ownership, so a
	// dropped connection is an unambiguous signal to reap leases.
	Work(grpc.BidiStreamingServer[WorkerMessage, AgentMessage]) error
	// PutObject streams object content; the response carries the canonical
	// ObjectRef after size/checksum verification and the durability boundary.
	PutObject(grpc.ClientStreamingServer[ObjectChunk, PutObjectResponse]) error
	// GetObject streams stored object content.
	GetObject(*ObjectGetRequest, grpc.ServerStreamingServer[ObjectChunk]) error
	// Status returns an agent status snapshot. Also serves as the readiness
	// probe used by the CLI and test harness.
	Status(context.Context, *StatusRequest) (*StatusSnapshot, error)
	// ForwardTask transfers a task to a peer agent (cluster, Phase 5).
	ForwardTask(context.Context, *ForwardedTask) (*ForwardTaskResponse, error)
	// ForwardCompletion returns a remote completion to the origin agent.
	ForwardCompletion(context.Context, *ForwardedCompletion) (*ForwardCompletionResponse, error)
	// Steal requests work from a peer agent (cluster, Phase 5).
	Steal(context.Context, *StealRequest) (*StealResponse, error)
	mustEmbedUnimplementedTaskwireControlServer()
}

// UnimplementedTaskwireControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskwireControlServer struct{}

func (UnimplementedTaskwireControlServer) Submit(context.Context, *TaskEnvelope) (*SubmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedTaskwireControlServer) WatchResults(*WatchResultsRequest, grpc.ServerStreamingServer[ResultNotification]) error {
	return status.Error(codes.Unimplemented, "method WatchResults not implemented")
}
func (UnimplementedTaskwireControlServer) AckResult(context.Context, *AckResultRequest) (*AckResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckResult not implemented")
}
func (UnimplementedTaskwireControlServer) Cancel(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedTaskwireControlServer) QueryTasks(context.Context, *TaskQuery) (*TaskSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryTasks not implemented")
}
func (UnimplementedTaskwireControlServer) RegisterTasks(context.Context, *TaskRegistration) (*RegisterTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterTasks not implemented")
}
func (UnimplementedTaskwireControlServer) Work(grpc.BidiStreamingServer[WorkerMessage, AgentMessage]) error {
	return status.Error(codes.Unimplemented, "method Work not implemented")
}
func (UnimplementedTaskwireControlServer) PutObject(grpc.ClientStreamingServer[ObjectChunk, PutObjectResponse]) error {
	return status.Error(codes.Unimplemented, "method PutObject not implemented")
}
func (UnimplementedTaskwireControlServer) GetObject(*ObjectGetRequest, grpc.ServerStreamingServer[ObjectChunk]) error {
	return status.Error(codes.Unimplemented, "method GetObject not implemented")
}
func (UnimplementedTaskwireControlServer) Status(context.Context, *StatusRequest) (*StatusSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedTaskwireControlServer) ForwardTask(context.Context, *ForwardedTask) (*ForwardTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardTask not implemented")
}
func (UnimplementedTaskwireControlServer) ForwardCompletion(context.Context, *ForwardedCompletion) (*ForwardCompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardCompletion not implemented")
}
func (UnimplementedTaskwireControlServer) Steal(context.Context, *StealRequest) (*StealResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Steal not implemented")
}
func (UnimplementedTaskwireControlServer) mustEmbedUnimplementedTaskwireControlServer() {}
func (UnimplementedTaskwireControlServer) testEmbeddedByValue()                         {}

// UnsafeTaskwireControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskwireControlServer will
// result in compilation errors.
type UnsafeTaskwireControlServer interface {
	mustEmbedUnimplementedTaskwireControlServer()
}

func RegisterTaskwireControlServer(s grpc.ServiceRegistrar, srv TaskwireControlServer) {
	// If the following call panics, it indicates UnimplementedTaskwireControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskwireControl_ServiceDesc, srv)
}

func _TaskwireControl_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskwireControlServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskwireControl_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskwireControlServer).Submit(ctx, req.(*TaskEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskwireControl_WatchResults_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchResultsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaskwireControlServer).WatchResults(m, &grpc.GenericServerStream[WatchResultsRequest, ResultNotification]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskwireControl_WatchResultsServer = grpc.ServerStreamingServer[ResultNotification]

func _TaskwireControl_AckResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskwireControlServer).AckResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskwireControl_AckResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskwireControlServer).AckResult(ctx, req.(*AckResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskwireControl_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskwireControlServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskwireControl_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskwireControlServer).Cancel(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskwireControl_QueryTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskwireControlServer).QueryTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskwireControl_QueryTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskwireControlServer).QueryTasks(ctx, req.(*TaskQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskwireControl_RegisterTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRegistration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskwireControlServer).RegisterTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskwireControl_RegisterTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskwireControlServer).RegisterTasks(ctx, req.(*TaskRegistration))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskwireControl_Work_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TaskwireControlServer).Work(&grpc.GenericServerStream[WorkerMessage, AgentMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskwireControl_WorkServer = grpc.BidiStreamingServer[WorkerMessage, AgentMessage]

func _TaskwireControl_PutObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TaskwireControlServer).PutObject(&grpc.GenericServerStream[ObjectChunk, PutObjectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskwireControl_PutObjectServer = grpc.ClientStreamingServer[ObjectChunk, PutObjectResponse]

func _TaskwireControl_GetObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ObjectGetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaskwireControlServer).GetObject(m, &grpc.GenericServerStream[ObjectGetRequest, ObjectChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskwireControl_GetObjectServer = grpc.ServerStreamingServer[ObjectChunk]

func _TaskwireControl_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskwireControlServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskwireControl_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskwireControlServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskwireControl_ForwardTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardedTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskwireControlServer).ForwardTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskwireControl_ForwardTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskwireControlServer).ForwardTask(ctx, req.(*ForwardedTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskwireControl_ForwardCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardedCompletion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskwireControlServer).ForwardCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskwireControl_ForwardCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskwireControlServer).ForwardCompletion(ctx, req.(*ForwardedCompletion))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskwireControl_Steal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskwireControlServer).Steal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskwireControl_Steal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskwireControlServer).Steal(ctx, req.(*StealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskwireControl_ServiceDesc is the grpc.ServiceDesc for TaskwireControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskwireControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "taskwire.v1.TaskwireControl",
	HandlerType: (*TaskwireControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _TaskwireControl_Submit_Handler,
		},
		{
			MethodName: "AckResult",
			Handler:    _TaskwireControl_AckResult_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _TaskwireControl_Cancel_Handler,
		},
		{
			MethodName: "QueryTasks",
			Handler:    _TaskwireControl_QueryTasks_Handler,
		},
		{
			MethodName: "RegisterTasks",
			Handler:    _TaskwireControl_RegisterTasks_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _TaskwireControl_Status_Handler,
		},
		{
			MethodName: "ForwardTask",
			Handler:    _TaskwireControl_ForwardTask_Handler,
		},
		{
			MethodName: "ForwardCompletion",
			Handler:    _TaskwireControl_ForwardCompletion_Handler,
		},
		{
			MethodName: "Steal",
			Handler:    _TaskwireControl_Steal_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchResults",
			Handler:       _TaskwireControl_WatchResults_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Work",
			Handler:       _TaskwireControl_Work_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PutObject",
			Handler:       _TaskwireControl_PutObject_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetObject",
			Handler:       _TaskwireControl_GetObject_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "taskwire/v1/control.proto",
}
